import { useEffect, useState } from "react";
import { Button, Card, Collapse, Form, Input, Switch, Tabs, Typography } from "antd";
import { Save, Settings as SettingsIcon, Upload, Plus, Trash2 } from "lucide-react";
import { api, responseData } from "@/lib/api";
import { ConsolePageLoading } from "@/components/console-page-loading";
import { toast } from "sonner";

interface SystemSetting { id: string; key: string; value: string; category: string; description: string | null; createdAt: string; updatedAt: string; }
interface DefaultSetting { key: string; value: string; category: string; description: string; }
interface PaymentSettings { basic: DefaultSetting[]; alipay: DefaultSetting[]; wechat: DefaultSetting[]; }
interface OperationSettings { basic: DefaultSetting[]; announcement: DefaultSetting[]; }
interface DefaultSettings { general: DefaultSetting[]; operation: OperationSettings; payment: PaymentSettings; oauth?: { basic: DefaultSetting[]; }; }
interface OAuthProvider { id: string; name: string; clientId: string; clientSecret: string; authorizationUrl: string; tokenUrl: string; userInfoUrl: string; scopes: string; userIdField: string; emailField: string; usernameField: string; roleField: string; }
interface OIDCProvider { name: string; issuer: string; clientId: string; clientSecret: string; scopes: string; }
const PEM_FILE_FIELDS = ["wechatPayPrivateKey", "wechatPayPublicKey", "wechatPayPaymentPublicKey"];
function createOAuthProviderID() { const browserCrypto = globalThis.crypto; return typeof browserCrypto?.randomUUID === "function" ? `oauth-${browserCrypto.randomUUID()}` : `oauth-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`; }

export default function SettingsPage() {
  const [settings, setSettings] = useState<Record<string, string>>({});
  const [defaultSettings, setDefaultSettings] = useState<DefaultSettings | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [oauthProviders, setOauthProviders] = useState<OAuthProvider[]>([]);
  const [oidcProvider, setOIDCProvider] = useState<OIDCProvider | null>(null);
  async function loadSettings() { const result = await api.system_settings_route_get(); const data = responseData<SystemSetting[]>(result); if (data) { const settingsMap = Object.fromEntries(data.map((setting) => [setting.key, setting.value])); try { if (settingsMap.oauthProviders) { const providers = JSON.parse(settingsMap.oauthProviders) as OAuthProvider[]; const legacyGitHub = providers.find((provider) => provider.id.trim().toLowerCase() === "github"); if (legacyGitHub) { settingsMap.githubOAuthClientId ||= legacyGitHub.clientId; settingsMap.githubOAuthClientSecret ||= legacyGitHub.clientSecret; } setOauthProviders(providers.filter((provider) => provider.id.trim().toLowerCase() !== "github")); } if (settingsMap.oidcProvider) setOIDCProvider(JSON.parse(settingsMap.oidcProvider) as OIDCProvider); } catch { /* keep empty provider list on parse failure */ } setSettings(settingsMap); } setIsLoading(false); }
  async function loadDefaultSettings() { const result = await api.system_settings_defaults_route_get(); const data = responseData<DefaultSettings>(result); if (data) setDefaultSettings(data); }
  useEffect(() => { loadSettings(); loadDefaultSettings(); }, []);
  function handleSettingChange(key: string, value: string) { setSettings((previous) => ({ ...previous, [key]: value })); }
  async function handleSave() { setIsSaving(true); const settingsToUpdate = [...Object.entries(settings).filter(([key]) => key !== "oauthProviders" && key !== "oidcProvider").map(([key, value]) => ({ key, value })), { key: "oauthProviders", value: JSON.stringify(oauthProviders) }, { key: "oidcProvider", value: oidcProvider ? JSON.stringify(oidcProvider) : "" }]; const result = await api.system_settings_route_put({ settings: settingsToUpdate }); if (result.success) toast.success("设置保存成功"); setIsSaving(false); }
  function addOAuthProvider() { setOauthProviders((previous) => [...previous, { id: createOAuthProviderID(), name: "", clientId: "", clientSecret: "", authorizationUrl: "", tokenUrl: "", userInfoUrl: "", scopes: "", userIdField: "", emailField: "", usernameField: "", roleField: "" }]); }
  function removeOAuthProvider(id: string) { setOauthProviders((previous) => previous.filter((provider) => provider.id !== id)); }
  function updateOAuthProvider(id: string, field: keyof OAuthProvider, value: string) { setOauthProviders((previous) => previous.map((provider) => provider.id === id ? { ...provider, [field]: value } : provider)); }
  function handleFileUpload(key: string) { const input = document.createElement("input"); input.type = "file"; input.accept = ".pem"; input.onchange = (event: Event) => { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = (loadEvent) => { handleSettingChange(key, String(loadEvent.target?.result || "").trim()); toast.success(`已成功读取 ${file.name}`); }; reader.onerror = () => toast.error("文件读取失败"); reader.readAsText(file); }; input.click(); }
  function renderSetting(setting: DefaultSetting) { const value = settings[setting.key] ?? setting.value; if (value === "true" || value === "false") return <Form.Item key={setting.key} label={setting.key} extra={setting.description}><Switch checked={value === "true"} onChange={(checked) => handleSettingChange(setting.key, checked ? "true" : "false")} /></Form.Item>; if (setting.key === "announcementContent") return <Form.Item key={setting.key} label={setting.key} extra={setting.description}><Input.TextArea value={value} onChange={(event) => handleSettingChange(setting.key, event.target.value)} placeholder={setting.value} rows={8} /></Form.Item>; if (PEM_FILE_FIELDS.includes(setting.key)) return <Form.Item key={setting.key} label={setting.key} extra={setting.description}><Button icon={<Upload size={16} />} onClick={() => handleFileUpload(setting.key)}>上传 .pem 文件</Button><Input.TextArea className="mt-2" value={value} onChange={(event) => handleSettingChange(setting.key, event.target.value)} placeholder={setting.value} rows={6} /></Form.Item>; return <Form.Item key={setting.key} label={setting.key} extra={setting.description}><Input value={value} onChange={(event) => handleSettingChange(setting.key, event.target.value)} placeholder={setting.value} /></Form.Item>; }
  function settingsCard(title: string, entries: DefaultSetting[] | undefined) { return <Card title={title}><Form layout="vertical">{entries?.map(renderSetting)}</Form></Card>; }
  function githubOAuthContent() { return <Card title="GitHub OAuth App"><Typography.Paragraph type="secondary">在 GitHub OAuth App 中将授权回调 URL 配置为“当前站点域名 + /api/auth/callback/github”。</Typography.Paragraph><Form layout="vertical"><Form.Item label="Client ID"><Input value={settings.githubOAuthClientId ?? ""} onChange={(event) => handleSettingChange("githubOAuthClientId", event.target.value)} autoComplete="off" /></Form.Item><Form.Item label="Client Secret"><Input.Password value={settings.githubOAuthClientSecret ?? ""} onChange={(event) => handleSettingChange("githubOAuthClientSecret", event.target.value)} autoComplete="new-password" /></Form.Item></Form></Card>; }
  function oidcContent() { const provider = oidcProvider ?? { name: "", issuer: "", clientId: "", clientSecret: "", scopes: "openid profile email" }; const update = (field: keyof OIDCProvider, value: string) => setOIDCProvider((previous) => ({ ...(previous ?? provider), [field]: value })); return <Card title="自定义 OIDC 提供商"><Typography.Paragraph type="secondary">填写发行方（Issuer）后，系统会自动读取其 OpenID Connect discovery 文档。授权回调 URL 为“当前站点域名 + /api/auth/callback/custom-oidc”。</Typography.Paragraph><Form layout="vertical"><div className="grid gap-4 md:grid-cols-2"><Form.Item label="显示名称"><Input value={provider.name} onChange={(event) => update("name", event.target.value)} placeholder="例如：公司统一登录" /></Form.Item><Form.Item label="Issuer URL"><Input value={provider.issuer} onChange={(event) => update("issuer", event.target.value)} placeholder="https://login.example.com" /></Form.Item><Form.Item label="Client ID"><Input value={provider.clientId} onChange={(event) => update("clientId", event.target.value)} autoComplete="off" /></Form.Item><Form.Item label="Client Secret"><Input.Password value={provider.clientSecret} onChange={(event) => update("clientSecret", event.target.value)} autoComplete="new-password" /></Form.Item><Form.Item className="md:col-span-2" label="Scopes" extra="系统始终会请求 openid；留空时默认使用 openid profile email。"><Input value={provider.scopes} onChange={(event) => update("scopes", event.target.value)} placeholder="openid profile email" /></Form.Item></div></Form></Card>; }
  function oauthContent() { return <Card title="自定义 OAuth 提供商" extra={<Button type="primary" icon={<Plus size={16} />} onClick={addOAuthProvider}>添加提供商</Button>}>{oauthProviders.length === 0 ? <Typography.Text type="secondary">暂无自定义 OAuth 提供商，点击上方按钮添加</Typography.Text> : <Collapse items={oauthProviders.map((provider) => ({ key: provider.id, label: provider.name || "未命名提供商", extra: <Button danger size="small" icon={<Trash2 size={16} />} onClick={(event) => { event.stopPropagation(); removeOAuthProvider(provider.id); }}>删除</Button>, children: <Form layout="vertical"><div className="grid gap-4 md:grid-cols-2">{([['name', '提供商名称', '例如: Google, Auth0', ''], ['clientId', 'Client ID', 'Client ID', ''], ['clientSecret', 'Client Secret', 'Client Secret', 'password'], ['authorizationUrl', 'AUTHORIZATION_URL', 'https://example.com/oauth/authorize', ''], ['tokenUrl', 'TOKEN_URL', 'https://example.com/oauth/token', ''], ['userInfoUrl', 'USER_INFO_URL', 'https://example.com/api/user', ''], ['scopes', 'Scopes', 'read,write,profile', ''], ['userIdField', '用户 ID 字段', 'id', ''], ['emailField', '邮箱字段', 'email', ''], ['usernameField', '用户名字段', 'username', ''], ['roleField', '角色字段（不生效）', 'role', '']] as const).map(([field, label, placeholder, type]) => <Form.Item key={field} label={label}><Input type={type || undefined} value={provider[field]} onChange={(event) => updateOAuthProvider(provider.id, field, event.target.value)} placeholder={placeholder} /></Form.Item>)}</div></Form> }))} />}</Card>; }
  if (isLoading || !defaultSettings) return <ConsolePageLoading />;
  const tabItems = [
    { key: "general", icon: <SettingsIcon size={16} className="inline-block align-middle" />, label: "通用设置", children: settingsCard("通用设置", defaultSettings.general) },
    { key: "operation", icon: <SettingsIcon size={16} className="inline-block align-middle" />, label: "运营设置", children: <div className="flex flex-col gap-6">{settingsCard("基本设置", defaultSettings.operation.basic)}{settingsCard("公告设置", defaultSettings.operation.announcement)}</div> },
    { key: "payment", icon: <SettingsIcon size={16} className="inline-block align-middle" />, label: "支付设置", children: <div className="flex flex-col gap-6">{settingsCard("基本设置", defaultSettings.payment.basic)}{settingsCard("支付宝设置", defaultSettings.payment.alipay)}{settingsCard("微信设置", defaultSettings.payment.wechat)}</div> },
    { key: "oauth", icon: <SettingsIcon size={16} className="inline-block align-middle" />, label: "OAuth 设置", children: <div className="flex flex-col gap-6">{githubOAuthContent()}{oidcContent()}{oauthContent()}</div> },
  ];
  return <div className="flex flex-col gap-6"><div className="flex items-center justify-between"><div><Typography.Title level={2}>系统设置</Typography.Title><Typography.Text type="secondary">管理系统配置</Typography.Text></div><Button type="primary" icon={<Save size={16} />} loading={isSaving} onClick={handleSave}>保存设置</Button></div><Tabs defaultActiveKey="general" items={tabItems} /></div>;
}
