// Code generated by ent, DO NOT EDIT.

package mcpusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the mcpusage type in the database.
	Label = "mcp_usage"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserId holds the string denoting the userid field in the database.
	FieldUserId = "userId"
	// FieldMcpId holds the string denoting the mcpid field in the database.
	FieldMcpId = "mcpId"
	// FieldCredits holds the string denoting the credits field in the database.
	FieldCredits = "credits"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "createdAt"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeMcp holds the string denoting the mcp edge name in mutations.
	EdgeMcp = "mcp"
	// Table holds the table name of the mcpusage in the database.
	Table = "McpUsage"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "McpUsage"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "User"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "userId"
	// McpTable is the table that holds the mcp relation/edge.
	McpTable = "McpUsage"
	// McpInverseTable is the table name for the McpService entity.
	// It exists in this package in order to avoid circular dependency with the "mcpservice" package.
	McpInverseTable = "McpService"
	// McpColumn is the table column denoting the mcp relation/edge.
	McpColumn = "mcpId"
)

// Columns holds all SQL columns for mcpusage fields.
var Columns = []string{
	FieldID,
	FieldUserId,
	FieldMcpId,
	FieldCredits,
	FieldStatus,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the McpUsage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserId orders the results by the userId field.
func ByUserId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserId, opts...).ToFunc()
}

// ByMcpId orders the results by the mcpId field.
func ByMcpId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMcpId, opts...).ToFunc()
}

// ByCredits orders the results by the credits field.
func ByCredits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredits, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByMcpField orders the results by mcp field.
func ByMcpField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMcpStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newMcpStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(McpInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, McpTable, McpColumn),
	)
}
