// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/nex-api/backend/ent/advertisement"
	"github.com/shuTwT/nex-api/backend/ent/predicate"
)

// AdvertisementUpdate is the builder for updating Advertisement entities.
type AdvertisementUpdate struct {
	config
	hooks    []Hook
	mutation *AdvertisementMutation
}

// Where appends a list predicates to the AdvertisementUpdate builder.
func (_u *AdvertisementUpdate) Where(ps ...predicate.Advertisement) *AdvertisementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetImage sets the "image" field.
func (_u *AdvertisementUpdate) SetImage(v string) *AdvertisementUpdate {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *AdvertisementUpdate) SetNillableImage(v *string) *AdvertisementUpdate {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// SetImageWidth sets the "imageWidth" field.
func (_u *AdvertisementUpdate) SetImageWidth(v int) *AdvertisementUpdate {
	_u.mutation.ResetImageWidth()
	_u.mutation.SetImageWidth(v)
	return _u
}

// SetNillableImageWidth sets the "imageWidth" field if the given value is not nil.
func (_u *AdvertisementUpdate) SetNillableImageWidth(v *int) *AdvertisementUpdate {
	if v != nil {
		_u.SetImageWidth(*v)
	}
	return _u
}

// AddImageWidth adds value to the "imageWidth" field.
func (_u *AdvertisementUpdate) AddImageWidth(v int) *AdvertisementUpdate {
	_u.mutation.AddImageWidth(v)
	return _u
}

// SetImageHeight sets the "imageHeight" field.
func (_u *AdvertisementUpdate) SetImageHeight(v int) *AdvertisementUpdate {
	_u.mutation.ResetImageHeight()
	_u.mutation.SetImageHeight(v)
	return _u
}

// SetNillableImageHeight sets the "imageHeight" field if the given value is not nil.
func (_u *AdvertisementUpdate) SetNillableImageHeight(v *int) *AdvertisementUpdate {
	if v != nil {
		_u.SetImageHeight(*v)
	}
	return _u
}

// AddImageHeight adds value to the "imageHeight" field.
func (_u *AdvertisementUpdate) AddImageHeight(v int) *AdvertisementUpdate {
	_u.mutation.AddImageHeight(v)
	return _u
}

// SetLink sets the "link" field.
func (_u *AdvertisementUpdate) SetLink(v string) *AdvertisementUpdate {
	_u.mutation.SetLink(v)
	return _u
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (_u *AdvertisementUpdate) SetNillableLink(v *string) *AdvertisementUpdate {
	if v != nil {
		_u.SetLink(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *AdvertisementUpdate) SetTitle(v string) *AdvertisementUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AdvertisementUpdate) SetNillableTitle(v *string) *AdvertisementUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *AdvertisementUpdate) SetPosition(v string) *AdvertisementUpdate {
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *AdvertisementUpdate) SetNillablePosition(v *string) *AdvertisementUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// SetIsActive sets the "isActive" field.
func (_u *AdvertisementUpdate) SetIsActive(v bool) *AdvertisementUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "isActive" field if the given value is not nil.
func (_u *AdvertisementUpdate) SetNillableIsActive(v *bool) *AdvertisementUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *AdvertisementUpdate) SetCreatedAt(v time.Time) *AdvertisementUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *AdvertisementUpdate) SetNillableCreatedAt(v *time.Time) *AdvertisementUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *AdvertisementUpdate) SetUpdatedAt(v time.Time) *AdvertisementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AdvertisementMutation object of the builder.
func (_u *AdvertisementUpdate) Mutation() *AdvertisementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdvertisementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdvertisementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdvertisementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdvertisementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdvertisementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := advertisement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AdvertisementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(advertisement.Table, advertisement.Columns, sqlgraph.NewFieldSpec(advertisement.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(advertisement.FieldImage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageWidth(); ok {
		_spec.SetField(advertisement.FieldImageWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImageWidth(); ok {
		_spec.AddField(advertisement.FieldImageWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ImageHeight(); ok {
		_spec.SetField(advertisement.FieldImageHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImageHeight(); ok {
		_spec.AddField(advertisement.FieldImageHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Link(); ok {
		_spec.SetField(advertisement.FieldLink, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(advertisement.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(advertisement.FieldPosition, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(advertisement.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(advertisement.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(advertisement.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{advertisement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdvertisementUpdateOne is the builder for updating a single Advertisement entity.
type AdvertisementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdvertisementMutation
}

// SetImage sets the "image" field.
func (_u *AdvertisementUpdateOne) SetImage(v string) *AdvertisementUpdateOne {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *AdvertisementUpdateOne) SetNillableImage(v *string) *AdvertisementUpdateOne {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// SetImageWidth sets the "imageWidth" field.
func (_u *AdvertisementUpdateOne) SetImageWidth(v int) *AdvertisementUpdateOne {
	_u.mutation.ResetImageWidth()
	_u.mutation.SetImageWidth(v)
	return _u
}

// SetNillableImageWidth sets the "imageWidth" field if the given value is not nil.
func (_u *AdvertisementUpdateOne) SetNillableImageWidth(v *int) *AdvertisementUpdateOne {
	if v != nil {
		_u.SetImageWidth(*v)
	}
	return _u
}

// AddImageWidth adds value to the "imageWidth" field.
func (_u *AdvertisementUpdateOne) AddImageWidth(v int) *AdvertisementUpdateOne {
	_u.mutation.AddImageWidth(v)
	return _u
}

// SetImageHeight sets the "imageHeight" field.
func (_u *AdvertisementUpdateOne) SetImageHeight(v int) *AdvertisementUpdateOne {
	_u.mutation.ResetImageHeight()
	_u.mutation.SetImageHeight(v)
	return _u
}

// SetNillableImageHeight sets the "imageHeight" field if the given value is not nil.
func (_u *AdvertisementUpdateOne) SetNillableImageHeight(v *int) *AdvertisementUpdateOne {
	if v != nil {
		_u.SetImageHeight(*v)
	}
	return _u
}

// AddImageHeight adds value to the "imageHeight" field.
func (_u *AdvertisementUpdateOne) AddImageHeight(v int) *AdvertisementUpdateOne {
	_u.mutation.AddImageHeight(v)
	return _u
}

// SetLink sets the "link" field.
func (_u *AdvertisementUpdateOne) SetLink(v string) *AdvertisementUpdateOne {
	_u.mutation.SetLink(v)
	return _u
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (_u *AdvertisementUpdateOne) SetNillableLink(v *string) *AdvertisementUpdateOne {
	if v != nil {
		_u.SetLink(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *AdvertisementUpdateOne) SetTitle(v string) *AdvertisementUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AdvertisementUpdateOne) SetNillableTitle(v *string) *AdvertisementUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *AdvertisementUpdateOne) SetPosition(v string) *AdvertisementUpdateOne {
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *AdvertisementUpdateOne) SetNillablePosition(v *string) *AdvertisementUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// SetIsActive sets the "isActive" field.
func (_u *AdvertisementUpdateOne) SetIsActive(v bool) *AdvertisementUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "isActive" field if the given value is not nil.
func (_u *AdvertisementUpdateOne) SetNillableIsActive(v *bool) *AdvertisementUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *AdvertisementUpdateOne) SetCreatedAt(v time.Time) *AdvertisementUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *AdvertisementUpdateOne) SetNillableCreatedAt(v *time.Time) *AdvertisementUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *AdvertisementUpdateOne) SetUpdatedAt(v time.Time) *AdvertisementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AdvertisementMutation object of the builder.
func (_u *AdvertisementUpdateOne) Mutation() *AdvertisementMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdvertisementUpdate builder.
func (_u *AdvertisementUpdateOne) Where(ps ...predicate.Advertisement) *AdvertisementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdvertisementUpdateOne) Select(field string, fields ...string) *AdvertisementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Advertisement entity.
func (_u *AdvertisementUpdateOne) Save(ctx context.Context) (*Advertisement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdvertisementUpdateOne) SaveX(ctx context.Context) *Advertisement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdvertisementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdvertisementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AdvertisementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := advertisement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AdvertisementUpdateOne) sqlSave(ctx context.Context) (_node *Advertisement, err error) {
	_spec := sqlgraph.NewUpdateSpec(advertisement.Table, advertisement.Columns, sqlgraph.NewFieldSpec(advertisement.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Advertisement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, advertisement.FieldID)
		for _, f := range fields {
			if !advertisement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != advertisement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(advertisement.FieldImage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageWidth(); ok {
		_spec.SetField(advertisement.FieldImageWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImageWidth(); ok {
		_spec.AddField(advertisement.FieldImageWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ImageHeight(); ok {
		_spec.SetField(advertisement.FieldImageHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImageHeight(); ok {
		_spec.AddField(advertisement.FieldImageHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Link(); ok {
		_spec.SetField(advertisement.FieldLink, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(advertisement.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(advertisement.FieldPosition, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(advertisement.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(advertisement.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(advertisement.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Advertisement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{advertisement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
