// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/nex-api/backend/ent/api"
	"github.com/shuTwT/nex-api/backend/ent/apicategory"
	"github.com/shuTwT/nex-api/backend/ent/apiparameter"
	"github.com/shuTwT/nex-api/backend/ent/apiresponse"
	"github.com/shuTwT/nex-api/backend/ent/apiusage"
	"github.com/shuTwT/nex-api/backend/ent/predicate"
)

// APIUpdate is the builder for updating Api entities.
type APIUpdate struct {
	config
	hooks    []Hook
	mutation *APIMutation
}

// Where appends a list predicates to the APIUpdate builder.
func (_u *APIUpdate) Where(ps ...predicate.Api) *APIUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *APIUpdate) SetName(v string) *APIUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *APIUpdate) SetNillableName(v *string) *APIUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAlias sets the "alias" field.
func (_u *APIUpdate) SetAlias(v string) *APIUpdate {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *APIUpdate) SetNillableAlias(v *string) *APIUpdate {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *APIUpdate) SetDescription(v string) *APIUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *APIUpdate) SetNillableDescription(v *string) *APIUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *APIUpdate) SetEndpoint(v string) *APIUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *APIUpdate) SetNillableEndpoint(v *string) *APIUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *APIUpdate) SetMethod(v string) *APIUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *APIUpdate) SetNillableMethod(v *string) *APIUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetCategoryId sets the "categoryId" field.
func (_u *APIUpdate) SetCategoryId(v string) *APIUpdate {
	_u.mutation.SetCategoryId(v)
	return _u
}

// SetNillableCategoryId sets the "categoryId" field if the given value is not nil.
func (_u *APIUpdate) SetNillableCategoryId(v *string) *APIUpdate {
	if v != nil {
		_u.SetCategoryId(*v)
	}
	return _u
}

// SetPricing sets the "pricing" field.
func (_u *APIUpdate) SetPricing(v int) *APIUpdate {
	_u.mutation.ResetPricing()
	_u.mutation.SetPricing(v)
	return _u
}

// SetNillablePricing sets the "pricing" field if the given value is not nil.
func (_u *APIUpdate) SetNillablePricing(v *int) *APIUpdate {
	if v != nil {
		_u.SetPricing(*v)
	}
	return _u
}

// AddPricing adds value to the "pricing" field.
func (_u *APIUpdate) AddPricing(v int) *APIUpdate {
	_u.mutation.AddPricing(v)
	return _u
}

// SetDocumentation sets the "documentation" field.
func (_u *APIUpdate) SetDocumentation(v string) *APIUpdate {
	_u.mutation.SetDocumentation(v)
	return _u
}

// SetNillableDocumentation sets the "documentation" field if the given value is not nil.
func (_u *APIUpdate) SetNillableDocumentation(v *string) *APIUpdate {
	if v != nil {
		_u.SetDocumentation(*v)
	}
	return _u
}

// ClearDocumentation clears the value of the "documentation" field.
func (_u *APIUpdate) ClearDocumentation() *APIUpdate {
	_u.mutation.ClearDocumentation()
	return _u
}

// SetPreScript sets the "preScript" field.
func (_u *APIUpdate) SetPreScript(v string) *APIUpdate {
	_u.mutation.SetPreScript(v)
	return _u
}

// SetNillablePreScript sets the "preScript" field if the given value is not nil.
func (_u *APIUpdate) SetNillablePreScript(v *string) *APIUpdate {
	if v != nil {
		_u.SetPreScript(*v)
	}
	return _u
}

// ClearPreScript clears the value of the "preScript" field.
func (_u *APIUpdate) ClearPreScript() *APIUpdate {
	_u.mutation.ClearPreScript()
	return _u
}

// SetPostScript sets the "postScript" field.
func (_u *APIUpdate) SetPostScript(v string) *APIUpdate {
	_u.mutation.SetPostScript(v)
	return _u
}

// SetNillablePostScript sets the "postScript" field if the given value is not nil.
func (_u *APIUpdate) SetNillablePostScript(v *string) *APIUpdate {
	if v != nil {
		_u.SetPostScript(*v)
	}
	return _u
}

// ClearPostScript clears the value of the "postScript" field.
func (_u *APIUpdate) ClearPostScript() *APIUpdate {
	_u.mutation.ClearPostScript()
	return _u
}

// SetIsActive sets the "isActive" field.
func (_u *APIUpdate) SetIsActive(v bool) *APIUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "isActive" field if the given value is not nil.
func (_u *APIUpdate) SetNillableIsActive(v *bool) *APIUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCallCount sets the "callCount" field.
func (_u *APIUpdate) SetCallCount(v int) *APIUpdate {
	_u.mutation.ResetCallCount()
	_u.mutation.SetCallCount(v)
	return _u
}

// SetNillableCallCount sets the "callCount" field if the given value is not nil.
func (_u *APIUpdate) SetNillableCallCount(v *int) *APIUpdate {
	if v != nil {
		_u.SetCallCount(*v)
	}
	return _u
}

// AddCallCount adds value to the "callCount" field.
func (_u *APIUpdate) AddCallCount(v int) *APIUpdate {
	_u.mutation.AddCallCount(v)
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *APIUpdate) SetCreatedAt(v time.Time) *APIUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *APIUpdate) SetNillableCreatedAt(v *time.Time) *APIUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *APIUpdate) SetUpdatedAt(v time.Time) *APIUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCategoryID sets the "category" edge to the ApiCategory entity by ID.
func (_u *APIUpdate) SetCategoryID(id string) *APIUpdate {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetCategory sets the "category" edge to the ApiCategory entity.
func (_u *APIUpdate) SetCategory(v *ApiCategory) *APIUpdate {
	return _u.SetCategoryID(v.ID)
}

// AddParameterIDs adds the "parameters" edge to the ApiParameter entity by IDs.
func (_u *APIUpdate) AddParameterIDs(ids ...string) *APIUpdate {
	_u.mutation.AddParameterIDs(ids...)
	return _u
}

// AddParameters adds the "parameters" edges to the ApiParameter entity.
func (_u *APIUpdate) AddParameters(v ...*ApiParameter) *APIUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParameterIDs(ids...)
}

// AddResponseIDs adds the "responses" edge to the ApiResponse entity by IDs.
func (_u *APIUpdate) AddResponseIDs(ids ...string) *APIUpdate {
	_u.mutation.AddResponseIDs(ids...)
	return _u
}

// AddResponses adds the "responses" edges to the ApiResponse entity.
func (_u *APIUpdate) AddResponses(v ...*ApiResponse) *APIUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResponseIDs(ids...)
}

// AddUsageRecordIDs adds the "usageRecords" edge to the ApiUsage entity by IDs.
func (_u *APIUpdate) AddUsageRecordIDs(ids ...string) *APIUpdate {
	_u.mutation.AddUsageRecordIDs(ids...)
	return _u
}

// AddUsageRecords adds the "usageRecords" edges to the ApiUsage entity.
func (_u *APIUpdate) AddUsageRecords(v ...*ApiUsage) *APIUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageRecordIDs(ids...)
}

// Mutation returns the APIMutation object of the builder.
func (_u *APIUpdate) Mutation() *APIMutation {
	return _u.mutation
}

// ClearCategory clears the "category" edge to the ApiCategory entity.
func (_u *APIUpdate) ClearCategory() *APIUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// ClearParameters clears all "parameters" edges to the ApiParameter entity.
func (_u *APIUpdate) ClearParameters() *APIUpdate {
	_u.mutation.ClearParameters()
	return _u
}

// RemoveParameterIDs removes the "parameters" edge to ApiParameter entities by IDs.
func (_u *APIUpdate) RemoveParameterIDs(ids ...string) *APIUpdate {
	_u.mutation.RemoveParameterIDs(ids...)
	return _u
}

// RemoveParameters removes "parameters" edges to ApiParameter entities.
func (_u *APIUpdate) RemoveParameters(v ...*ApiParameter) *APIUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParameterIDs(ids...)
}

// ClearResponses clears all "responses" edges to the ApiResponse entity.
func (_u *APIUpdate) ClearResponses() *APIUpdate {
	_u.mutation.ClearResponses()
	return _u
}

// RemoveResponseIDs removes the "responses" edge to ApiResponse entities by IDs.
func (_u *APIUpdate) RemoveResponseIDs(ids ...string) *APIUpdate {
	_u.mutation.RemoveResponseIDs(ids...)
	return _u
}

// RemoveResponses removes "responses" edges to ApiResponse entities.
func (_u *APIUpdate) RemoveResponses(v ...*ApiResponse) *APIUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResponseIDs(ids...)
}

// ClearUsageRecords clears all "usageRecords" edges to the ApiUsage entity.
func (_u *APIUpdate) ClearUsageRecords() *APIUpdate {
	_u.mutation.ClearUsageRecords()
	return _u
}

// RemoveUsageRecordIDs removes the "usageRecords" edge to ApiUsage entities by IDs.
func (_u *APIUpdate) RemoveUsageRecordIDs(ids ...string) *APIUpdate {
	_u.mutation.RemoveUsageRecordIDs(ids...)
	return _u
}

// RemoveUsageRecords removes "usageRecords" edges to ApiUsage entities.
func (_u *APIUpdate) RemoveUsageRecords(v ...*ApiUsage) *APIUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageRecordIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := api.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIUpdate) check() error {
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Api.category"`)
	}
	return nil
}

func (_u *APIUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(api.Table, api.Columns, sqlgraph.NewFieldSpec(api.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(api.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(api.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(api.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(api.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(api.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pricing(); ok {
		_spec.SetField(api.FieldPricing, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPricing(); ok {
		_spec.AddField(api.FieldPricing, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Documentation(); ok {
		_spec.SetField(api.FieldDocumentation, field.TypeString, value)
	}
	if _u.mutation.DocumentationCleared() {
		_spec.ClearField(api.FieldDocumentation, field.TypeString)
	}
	if value, ok := _u.mutation.PreScript(); ok {
		_spec.SetField(api.FieldPreScript, field.TypeString, value)
	}
	if _u.mutation.PreScriptCleared() {
		_spec.ClearField(api.FieldPreScript, field.TypeString)
	}
	if value, ok := _u.mutation.PostScript(); ok {
		_spec.SetField(api.FieldPostScript, field.TypeString, value)
	}
	if _u.mutation.PostScriptCleared() {
		_spec.ClearField(api.FieldPostScript, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(api.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CallCount(); ok {
		_spec.SetField(api.FieldCallCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCallCount(); ok {
		_spec.AddField(api.FieldCallCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(api.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(api.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.CategoryTable,
			Columns: []string{api.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apicategory.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.CategoryTable,
			Columns: []string{api.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apicategory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParametersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ParametersTable,
			Columns: []string{api.ParametersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiparameter.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParametersIDs(); len(nodes) > 0 && !_u.mutation.ParametersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ParametersTable,
			Columns: []string{api.ParametersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiparameter.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParametersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ParametersTable,
			Columns: []string{api.ParametersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiparameter.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResponsesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponsesTable,
			Columns: []string{api.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiresponse.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResponsesIDs(); len(nodes) > 0 && !_u.mutation.ResponsesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponsesTable,
			Columns: []string{api.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiresponse.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResponsesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponsesTable,
			Columns: []string{api.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiresponse.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.UsageRecordsTable,
			Columns: []string{api.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageRecordsIDs(); len(nodes) > 0 && !_u.mutation.UsageRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.UsageRecordsTable,
			Columns: []string{api.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.UsageRecordsTable,
			Columns: []string{api.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{api.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIUpdateOne is the builder for updating a single Api entity.
type APIUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APIMutation
}

// SetName sets the "name" field.
func (_u *APIUpdateOne) SetName(v string) *APIUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableName(v *string) *APIUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAlias sets the "alias" field.
func (_u *APIUpdateOne) SetAlias(v string) *APIUpdateOne {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableAlias(v *string) *APIUpdateOne {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *APIUpdateOne) SetDescription(v string) *APIUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableDescription(v *string) *APIUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *APIUpdateOne) SetEndpoint(v string) *APIUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableEndpoint(v *string) *APIUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *APIUpdateOne) SetMethod(v string) *APIUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableMethod(v *string) *APIUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetCategoryId sets the "categoryId" field.
func (_u *APIUpdateOne) SetCategoryId(v string) *APIUpdateOne {
	_u.mutation.SetCategoryId(v)
	return _u
}

// SetNillableCategoryId sets the "categoryId" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableCategoryId(v *string) *APIUpdateOne {
	if v != nil {
		_u.SetCategoryId(*v)
	}
	return _u
}

// SetPricing sets the "pricing" field.
func (_u *APIUpdateOne) SetPricing(v int) *APIUpdateOne {
	_u.mutation.ResetPricing()
	_u.mutation.SetPricing(v)
	return _u
}

// SetNillablePricing sets the "pricing" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillablePricing(v *int) *APIUpdateOne {
	if v != nil {
		_u.SetPricing(*v)
	}
	return _u
}

// AddPricing adds value to the "pricing" field.
func (_u *APIUpdateOne) AddPricing(v int) *APIUpdateOne {
	_u.mutation.AddPricing(v)
	return _u
}

// SetDocumentation sets the "documentation" field.
func (_u *APIUpdateOne) SetDocumentation(v string) *APIUpdateOne {
	_u.mutation.SetDocumentation(v)
	return _u
}

// SetNillableDocumentation sets the "documentation" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableDocumentation(v *string) *APIUpdateOne {
	if v != nil {
		_u.SetDocumentation(*v)
	}
	return _u
}

// ClearDocumentation clears the value of the "documentation" field.
func (_u *APIUpdateOne) ClearDocumentation() *APIUpdateOne {
	_u.mutation.ClearDocumentation()
	return _u
}

// SetPreScript sets the "preScript" field.
func (_u *APIUpdateOne) SetPreScript(v string) *APIUpdateOne {
	_u.mutation.SetPreScript(v)
	return _u
}

// SetNillablePreScript sets the "preScript" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillablePreScript(v *string) *APIUpdateOne {
	if v != nil {
		_u.SetPreScript(*v)
	}
	return _u
}

// ClearPreScript clears the value of the "preScript" field.
func (_u *APIUpdateOne) ClearPreScript() *APIUpdateOne {
	_u.mutation.ClearPreScript()
	return _u
}

// SetPostScript sets the "postScript" field.
func (_u *APIUpdateOne) SetPostScript(v string) *APIUpdateOne {
	_u.mutation.SetPostScript(v)
	return _u
}

// SetNillablePostScript sets the "postScript" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillablePostScript(v *string) *APIUpdateOne {
	if v != nil {
		_u.SetPostScript(*v)
	}
	return _u
}

// ClearPostScript clears the value of the "postScript" field.
func (_u *APIUpdateOne) ClearPostScript() *APIUpdateOne {
	_u.mutation.ClearPostScript()
	return _u
}

// SetIsActive sets the "isActive" field.
func (_u *APIUpdateOne) SetIsActive(v bool) *APIUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "isActive" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableIsActive(v *bool) *APIUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCallCount sets the "callCount" field.
func (_u *APIUpdateOne) SetCallCount(v int) *APIUpdateOne {
	_u.mutation.ResetCallCount()
	_u.mutation.SetCallCount(v)
	return _u
}

// SetNillableCallCount sets the "callCount" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableCallCount(v *int) *APIUpdateOne {
	if v != nil {
		_u.SetCallCount(*v)
	}
	return _u
}

// AddCallCount adds value to the "callCount" field.
func (_u *APIUpdateOne) AddCallCount(v int) *APIUpdateOne {
	_u.mutation.AddCallCount(v)
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *APIUpdateOne) SetCreatedAt(v time.Time) *APIUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *APIUpdateOne) SetNillableCreatedAt(v *time.Time) *APIUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *APIUpdateOne) SetUpdatedAt(v time.Time) *APIUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCategoryID sets the "category" edge to the ApiCategory entity by ID.
func (_u *APIUpdateOne) SetCategoryID(id string) *APIUpdateOne {
	_u.mutation.SetCategoryID(id)
	return _u
}

// SetCategory sets the "category" edge to the ApiCategory entity.
func (_u *APIUpdateOne) SetCategory(v *ApiCategory) *APIUpdateOne {
	return _u.SetCategoryID(v.ID)
}

// AddParameterIDs adds the "parameters" edge to the ApiParameter entity by IDs.
func (_u *APIUpdateOne) AddParameterIDs(ids ...string) *APIUpdateOne {
	_u.mutation.AddParameterIDs(ids...)
	return _u
}

// AddParameters adds the "parameters" edges to the ApiParameter entity.
func (_u *APIUpdateOne) AddParameters(v ...*ApiParameter) *APIUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParameterIDs(ids...)
}

// AddResponseIDs adds the "responses" edge to the ApiResponse entity by IDs.
func (_u *APIUpdateOne) AddResponseIDs(ids ...string) *APIUpdateOne {
	_u.mutation.AddResponseIDs(ids...)
	return _u
}

// AddResponses adds the "responses" edges to the ApiResponse entity.
func (_u *APIUpdateOne) AddResponses(v ...*ApiResponse) *APIUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResponseIDs(ids...)
}

// AddUsageRecordIDs adds the "usageRecords" edge to the ApiUsage entity by IDs.
func (_u *APIUpdateOne) AddUsageRecordIDs(ids ...string) *APIUpdateOne {
	_u.mutation.AddUsageRecordIDs(ids...)
	return _u
}

// AddUsageRecords adds the "usageRecords" edges to the ApiUsage entity.
func (_u *APIUpdateOne) AddUsageRecords(v ...*ApiUsage) *APIUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageRecordIDs(ids...)
}

// Mutation returns the APIMutation object of the builder.
func (_u *APIUpdateOne) Mutation() *APIMutation {
	return _u.mutation
}

// ClearCategory clears the "category" edge to the ApiCategory entity.
func (_u *APIUpdateOne) ClearCategory() *APIUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// ClearParameters clears all "parameters" edges to the ApiParameter entity.
func (_u *APIUpdateOne) ClearParameters() *APIUpdateOne {
	_u.mutation.ClearParameters()
	return _u
}

// RemoveParameterIDs removes the "parameters" edge to ApiParameter entities by IDs.
func (_u *APIUpdateOne) RemoveParameterIDs(ids ...string) *APIUpdateOne {
	_u.mutation.RemoveParameterIDs(ids...)
	return _u
}

// RemoveParameters removes "parameters" edges to ApiParameter entities.
func (_u *APIUpdateOne) RemoveParameters(v ...*ApiParameter) *APIUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParameterIDs(ids...)
}

// ClearResponses clears all "responses" edges to the ApiResponse entity.
func (_u *APIUpdateOne) ClearResponses() *APIUpdateOne {
	_u.mutation.ClearResponses()
	return _u
}

// RemoveResponseIDs removes the "responses" edge to ApiResponse entities by IDs.
func (_u *APIUpdateOne) RemoveResponseIDs(ids ...string) *APIUpdateOne {
	_u.mutation.RemoveResponseIDs(ids...)
	return _u
}

// RemoveResponses removes "responses" edges to ApiResponse entities.
func (_u *APIUpdateOne) RemoveResponses(v ...*ApiResponse) *APIUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResponseIDs(ids...)
}

// ClearUsageRecords clears all "usageRecords" edges to the ApiUsage entity.
func (_u *APIUpdateOne) ClearUsageRecords() *APIUpdateOne {
	_u.mutation.ClearUsageRecords()
	return _u
}

// RemoveUsageRecordIDs removes the "usageRecords" edge to ApiUsage entities by IDs.
func (_u *APIUpdateOne) RemoveUsageRecordIDs(ids ...string) *APIUpdateOne {
	_u.mutation.RemoveUsageRecordIDs(ids...)
	return _u
}

// RemoveUsageRecords removes "usageRecords" edges to ApiUsage entities.
func (_u *APIUpdateOne) RemoveUsageRecords(v ...*ApiUsage) *APIUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageRecordIDs(ids...)
}

// Where appends a list predicates to the APIUpdate builder.
func (_u *APIUpdateOne) Where(ps ...predicate.Api) *APIUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIUpdateOne) Select(field string, fields ...string) *APIUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Api entity.
func (_u *APIUpdateOne) Save(ctx context.Context) (*Api, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIUpdateOne) SaveX(ctx context.Context) *Api {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := api.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIUpdateOne) check() error {
	if _u.mutation.CategoryCleared() && len(_u.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Api.category"`)
	}
	return nil
}

func (_u *APIUpdateOne) sqlSave(ctx context.Context) (_node *Api, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(api.Table, api.Columns, sqlgraph.NewFieldSpec(api.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Api.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, api.FieldID)
		for _, f := range fields {
			if !api.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != api.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(api.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(api.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(api.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(api.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(api.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pricing(); ok {
		_spec.SetField(api.FieldPricing, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPricing(); ok {
		_spec.AddField(api.FieldPricing, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Documentation(); ok {
		_spec.SetField(api.FieldDocumentation, field.TypeString, value)
	}
	if _u.mutation.DocumentationCleared() {
		_spec.ClearField(api.FieldDocumentation, field.TypeString)
	}
	if value, ok := _u.mutation.PreScript(); ok {
		_spec.SetField(api.FieldPreScript, field.TypeString, value)
	}
	if _u.mutation.PreScriptCleared() {
		_spec.ClearField(api.FieldPreScript, field.TypeString)
	}
	if value, ok := _u.mutation.PostScript(); ok {
		_spec.SetField(api.FieldPostScript, field.TypeString, value)
	}
	if _u.mutation.PostScriptCleared() {
		_spec.ClearField(api.FieldPostScript, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(api.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CallCount(); ok {
		_spec.SetField(api.FieldCallCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCallCount(); ok {
		_spec.AddField(api.FieldCallCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(api.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(api.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.CategoryTable,
			Columns: []string{api.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apicategory.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   api.CategoryTable,
			Columns: []string{api.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apicategory.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParametersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ParametersTable,
			Columns: []string{api.ParametersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiparameter.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParametersIDs(); len(nodes) > 0 && !_u.mutation.ParametersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ParametersTable,
			Columns: []string{api.ParametersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiparameter.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParametersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ParametersTable,
			Columns: []string{api.ParametersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiparameter.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResponsesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponsesTable,
			Columns: []string{api.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiresponse.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResponsesIDs(); len(nodes) > 0 && !_u.mutation.ResponsesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponsesTable,
			Columns: []string{api.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiresponse.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResponsesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.ResponsesTable,
			Columns: []string{api.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiresponse.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.UsageRecordsTable,
			Columns: []string{api.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageRecordsIDs(); len(nodes) > 0 && !_u.mutation.UsageRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.UsageRecordsTable,
			Columns: []string{api.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   api.UsageRecordsTable,
			Columns: []string{api.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Api{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{api.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
