// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/nex-api/backend/ent/apicategory"
	"github.com/shuTwT/nex-api/backend/ent/predicate"
)

// ApiCategoryDelete is the builder for deleting a ApiCategory entity.
type ApiCategoryDelete struct {
	config
	hooks    []Hook
	mutation *ApiCategoryMutation
}

// Where appends a list predicates to the ApiCategoryDelete builder.
func (_d *ApiCategoryDelete) Where(ps ...predicate.ApiCategory) *ApiCategoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ApiCategoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ApiCategoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ApiCategoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(apicategory.Table, sqlgraph.NewFieldSpec(apicategory.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ApiCategoryDeleteOne is the builder for deleting a single ApiCategory entity.
type ApiCategoryDeleteOne struct {
	_d *ApiCategoryDelete
}

// Where appends a list predicates to the ApiCategoryDelete builder.
func (_d *ApiCategoryDeleteOne) Where(ps ...predicate.ApiCategory) *ApiCategoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ApiCategoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{apicategory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ApiCategoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
