// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/nex-api/backend/ent/apitoken"
	"github.com/shuTwT/nex-api/backend/ent/predicate"
	"github.com/shuTwT/nex-api/backend/ent/user"
)

// ApiTokenUpdate is the builder for updating ApiToken entities.
type ApiTokenUpdate struct {
	config
	hooks    []Hook
	mutation *ApiTokenMutation
}

// Where appends a list predicates to the ApiTokenUpdate builder.
func (_u *ApiTokenUpdate) Where(ps ...predicate.ApiToken) *ApiTokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserId sets the "userId" field.
func (_u *ApiTokenUpdate) SetUserId(v string) *ApiTokenUpdate {
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (_u *ApiTokenUpdate) SetNillableUserId(v *string) *ApiTokenUpdate {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ApiTokenUpdate) SetName(v string) *ApiTokenUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApiTokenUpdate) SetNillableName(v *string) *ApiTokenUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *ApiTokenUpdate) SetToken(v string) *ApiTokenUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *ApiTokenUpdate) SetNillableToken(v *string) *ApiTokenUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetPermissions sets the "permissions" field.
func (_u *ApiTokenUpdate) SetPermissions(v string) *ApiTokenUpdate {
	_u.mutation.SetPermissions(v)
	return _u
}

// SetNillablePermissions sets the "permissions" field if the given value is not nil.
func (_u *ApiTokenUpdate) SetNillablePermissions(v *string) *ApiTokenUpdate {
	if v != nil {
		_u.SetPermissions(*v)
	}
	return _u
}

// SetLastUsedAt sets the "lastUsedAt" field.
func (_u *ApiTokenUpdate) SetLastUsedAt(v time.Time) *ApiTokenUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "lastUsedAt" field if the given value is not nil.
func (_u *ApiTokenUpdate) SetNillableLastUsedAt(v *time.Time) *ApiTokenUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "lastUsedAt" field.
func (_u *ApiTokenUpdate) ClearLastUsedAt() *ApiTokenUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetExpiresAt sets the "expiresAt" field.
func (_u *ApiTokenUpdate) SetExpiresAt(v time.Time) *ApiTokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expiresAt" field if the given value is not nil.
func (_u *ApiTokenUpdate) SetNillableExpiresAt(v *time.Time) *ApiTokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expiresAt" field.
func (_u *ApiTokenUpdate) ClearExpiresAt() *ApiTokenUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetIsActive sets the "isActive" field.
func (_u *ApiTokenUpdate) SetIsActive(v bool) *ApiTokenUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "isActive" field if the given value is not nil.
func (_u *ApiTokenUpdate) SetNillableIsActive(v *bool) *ApiTokenUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *ApiTokenUpdate) SetCreatedAt(v time.Time) *ApiTokenUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *ApiTokenUpdate) SetNillableCreatedAt(v *time.Time) *ApiTokenUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *ApiTokenUpdate) SetUpdatedAt(v time.Time) *ApiTokenUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ApiTokenUpdate) SetUserID(id string) *ApiTokenUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ApiTokenUpdate) SetUser(v *User) *ApiTokenUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ApiTokenMutation object of the builder.
func (_u *ApiTokenUpdate) Mutation() *ApiTokenMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ApiTokenUpdate) ClearUser() *ApiTokenUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApiTokenUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApiTokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiTokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ApiTokenUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apitoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiTokenUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiToken.user"`)
	}
	return nil
}

func (_u *ApiTokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apitoken.Table, apitoken.Columns, sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apitoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(apitoken.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Permissions(); ok {
		_spec.SetField(apitoken.FieldPermissions, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(apitoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(apitoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(apitoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(apitoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(apitoken.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(apitoken.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apitoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.UserTable,
			Columns: []string{apitoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.UserTable,
			Columns: []string{apitoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apitoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApiTokenUpdateOne is the builder for updating a single ApiToken entity.
type ApiTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApiTokenMutation
}

// SetUserId sets the "userId" field.
func (_u *ApiTokenUpdateOne) SetUserId(v string) *ApiTokenUpdateOne {
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (_u *ApiTokenUpdateOne) SetNillableUserId(v *string) *ApiTokenUpdateOne {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ApiTokenUpdateOne) SetName(v string) *ApiTokenUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApiTokenUpdateOne) SetNillableName(v *string) *ApiTokenUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *ApiTokenUpdateOne) SetToken(v string) *ApiTokenUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *ApiTokenUpdateOne) SetNillableToken(v *string) *ApiTokenUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetPermissions sets the "permissions" field.
func (_u *ApiTokenUpdateOne) SetPermissions(v string) *ApiTokenUpdateOne {
	_u.mutation.SetPermissions(v)
	return _u
}

// SetNillablePermissions sets the "permissions" field if the given value is not nil.
func (_u *ApiTokenUpdateOne) SetNillablePermissions(v *string) *ApiTokenUpdateOne {
	if v != nil {
		_u.SetPermissions(*v)
	}
	return _u
}

// SetLastUsedAt sets the "lastUsedAt" field.
func (_u *ApiTokenUpdateOne) SetLastUsedAt(v time.Time) *ApiTokenUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "lastUsedAt" field if the given value is not nil.
func (_u *ApiTokenUpdateOne) SetNillableLastUsedAt(v *time.Time) *ApiTokenUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "lastUsedAt" field.
func (_u *ApiTokenUpdateOne) ClearLastUsedAt() *ApiTokenUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetExpiresAt sets the "expiresAt" field.
func (_u *ApiTokenUpdateOne) SetExpiresAt(v time.Time) *ApiTokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expiresAt" field if the given value is not nil.
func (_u *ApiTokenUpdateOne) SetNillableExpiresAt(v *time.Time) *ApiTokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expiresAt" field.
func (_u *ApiTokenUpdateOne) ClearExpiresAt() *ApiTokenUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetIsActive sets the "isActive" field.
func (_u *ApiTokenUpdateOne) SetIsActive(v bool) *ApiTokenUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "isActive" field if the given value is not nil.
func (_u *ApiTokenUpdateOne) SetNillableIsActive(v *bool) *ApiTokenUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *ApiTokenUpdateOne) SetCreatedAt(v time.Time) *ApiTokenUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *ApiTokenUpdateOne) SetNillableCreatedAt(v *time.Time) *ApiTokenUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *ApiTokenUpdateOne) SetUpdatedAt(v time.Time) *ApiTokenUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ApiTokenUpdateOne) SetUserID(id string) *ApiTokenUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ApiTokenUpdateOne) SetUser(v *User) *ApiTokenUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ApiTokenMutation object of the builder.
func (_u *ApiTokenUpdateOne) Mutation() *ApiTokenMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ApiTokenUpdateOne) ClearUser() *ApiTokenUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ApiTokenUpdate builder.
func (_u *ApiTokenUpdateOne) Where(ps ...predicate.ApiToken) *ApiTokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApiTokenUpdateOne) Select(field string, fields ...string) *ApiTokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ApiToken entity.
func (_u *ApiTokenUpdateOne) Save(ctx context.Context) (*ApiToken, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiTokenUpdateOne) SaveX(ctx context.Context) *ApiToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApiTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiTokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ApiTokenUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apitoken.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiTokenUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiToken.user"`)
	}
	return nil
}

func (_u *ApiTokenUpdateOne) sqlSave(ctx context.Context) (_node *ApiToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apitoken.Table, apitoken.Columns, sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApiToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apitoken.FieldID)
		for _, f := range fields {
			if !apitoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apitoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apitoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(apitoken.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Permissions(); ok {
		_spec.SetField(apitoken.FieldPermissions, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(apitoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(apitoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(apitoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(apitoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(apitoken.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(apitoken.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apitoken.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.UserTable,
			Columns: []string{apitoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apitoken.UserTable,
			Columns: []string{apitoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ApiToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apitoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
