// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shuTwT/nex-api/backend/ent/mcpservice"
	"github.com/shuTwT/nex-api/backend/ent/mcpusage"
	"github.com/shuTwT/nex-api/backend/ent/user"
)

// McpUsage is the model entity for the McpUsage schema.
type McpUsage struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserId holds the value of the "userId" field.
	UserId string `json:"userId,omitempty"`
	// McpId holds the value of the "mcpId" field.
	McpId string `json:"mcpId,omitempty"`
	// Credits holds the value of the "credits" field.
	Credits int `json:"credits,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the McpUsageQuery when eager-loading is set.
	Edges        McpUsageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// McpUsageEdges holds the relations/edges for other nodes in the graph.
type McpUsageEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Mcp holds the value of the mcp edge.
	Mcp *McpService `json:"mcp,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e McpUsageEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// McpOrErr returns the Mcp value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e McpUsageEdges) McpOrErr() (*McpService, error) {
	if e.Mcp != nil {
		return e.Mcp, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: mcpservice.Label}
	}
	return nil, &NotLoadedError{edge: "mcp"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*McpUsage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mcpusage.FieldCredits:
			values[i] = new(sql.NullInt64)
		case mcpusage.FieldID, mcpusage.FieldUserId, mcpusage.FieldMcpId, mcpusage.FieldStatus:
			values[i] = new(sql.NullString)
		case mcpusage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the McpUsage fields.
func (_m *McpUsage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mcpusage.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case mcpusage.FieldUserId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field userId", values[i])
			} else if value.Valid {
				_m.UserId = value.String
			}
		case mcpusage.FieldMcpId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mcpId", values[i])
			} else if value.Valid {
				_m.McpId = value.String
			}
		case mcpusage.FieldCredits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credits", values[i])
			} else if value.Valid {
				_m.Credits = int(value.Int64)
			}
		case mcpusage.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case mcpusage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the McpUsage.
// This includes values selected through modifiers, order, etc.
func (_m *McpUsage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the McpUsage entity.
func (_m *McpUsage) QueryUser() *UserQuery {
	return NewMcpUsageClient(_m.config).QueryUser(_m)
}

// QueryMcp queries the "mcp" edge of the McpUsage entity.
func (_m *McpUsage) QueryMcp() *McpServiceQuery {
	return NewMcpUsageClient(_m.config).QueryMcp(_m)
}

// Update returns a builder for updating this McpUsage.
// Note that you need to call McpUsage.Unwrap() before calling this method if this McpUsage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *McpUsage) Update() *McpUsageUpdateOne {
	return NewMcpUsageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the McpUsage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *McpUsage) Unwrap() *McpUsage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: McpUsage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *McpUsage) String() string {
	var builder strings.Builder
	builder.WriteString("McpUsage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("userId=")
	builder.WriteString(_m.UserId)
	builder.WriteString(", ")
	builder.WriteString("mcpId=")
	builder.WriteString(_m.McpId)
	builder.WriteString(", ")
	builder.WriteString("credits=")
	builder.WriteString(fmt.Sprintf("%v", _m.Credits))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// McpUsages is a parsable slice of McpUsage.
type McpUsages []*McpUsage
