// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/nex-api/backend/ent/predicate"
	"github.com/shuTwT/nex-api/backend/ent/subscription"
	"github.com/shuTwT/nex-api/backend/ent/subscriptionplan"
)

// SubscriptionPlanUpdate is the builder for updating SubscriptionPlan entities.
type SubscriptionPlanUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionPlanMutation
}

// Where appends a list predicates to the SubscriptionPlanUpdate builder.
func (_u *SubscriptionPlanUpdate) Where(ps ...predicate.SubscriptionPlan) *SubscriptionPlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *SubscriptionPlanUpdate) SetTitle(v string) *SubscriptionPlanUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableTitle(v *string) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *SubscriptionPlanUpdate) SetPrice(v float64) *SubscriptionPlanUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillablePrice(v *float64) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *SubscriptionPlanUpdate) AddPrice(v float64) *SubscriptionPlanUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetTotalCredits sets the "totalCredits" field.
func (_u *SubscriptionPlanUpdate) SetTotalCredits(v int) *SubscriptionPlanUpdate {
	_u.mutation.ResetTotalCredits()
	_u.mutation.SetTotalCredits(v)
	return _u
}

// SetNillableTotalCredits sets the "totalCredits" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableTotalCredits(v *int) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetTotalCredits(*v)
	}
	return _u
}

// AddTotalCredits adds value to the "totalCredits" field.
func (_u *SubscriptionPlanUpdate) AddTotalCredits(v int) *SubscriptionPlanUpdate {
	_u.mutation.AddTotalCredits(v)
	return _u
}

// SetSortOrder sets the "sortOrder" field.
func (_u *SubscriptionPlanUpdate) SetSortOrder(v int) *SubscriptionPlanUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sortOrder" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableSortOrder(v *int) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sortOrder" field.
func (_u *SubscriptionPlanUpdate) AddSortOrder(v int) *SubscriptionPlanUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetValidityDuration sets the "validityDuration" field.
func (_u *SubscriptionPlanUpdate) SetValidityDuration(v int) *SubscriptionPlanUpdate {
	_u.mutation.ResetValidityDuration()
	_u.mutation.SetValidityDuration(v)
	return _u
}

// SetNillableValidityDuration sets the "validityDuration" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableValidityDuration(v *int) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetValidityDuration(*v)
	}
	return _u
}

// AddValidityDuration adds value to the "validityDuration" field.
func (_u *SubscriptionPlanUpdate) AddValidityDuration(v int) *SubscriptionPlanUpdate {
	_u.mutation.AddValidityDuration(v)
	return _u
}

// SetValidityUnit sets the "validityUnit" field.
func (_u *SubscriptionPlanUpdate) SetValidityUnit(v string) *SubscriptionPlanUpdate {
	_u.mutation.SetValidityUnit(v)
	return _u
}

// SetNillableValidityUnit sets the "validityUnit" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableValidityUnit(v *string) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetValidityUnit(*v)
	}
	return _u
}

// SetCreditResetCycle sets the "creditResetCycle" field.
func (_u *SubscriptionPlanUpdate) SetCreditResetCycle(v string) *SubscriptionPlanUpdate {
	_u.mutation.SetCreditResetCycle(v)
	return _u
}

// SetNillableCreditResetCycle sets the "creditResetCycle" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableCreditResetCycle(v *string) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetCreditResetCycle(*v)
	}
	return _u
}

// SetIsActive sets the "isActive" field.
func (_u *SubscriptionPlanUpdate) SetIsActive(v bool) *SubscriptionPlanUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "isActive" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableIsActive(v *bool) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *SubscriptionPlanUpdate) SetCreatedAt(v time.Time) *SubscriptionPlanUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *SubscriptionPlanUpdate) SetNillableCreatedAt(v *time.Time) *SubscriptionPlanUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *SubscriptionPlanUpdate) SetUpdatedAt(v time.Time) *SubscriptionPlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddSubscriptionIDs adds the "subscriptions" edge to the Subscription entity by IDs.
func (_u *SubscriptionPlanUpdate) AddSubscriptionIDs(ids ...string) *SubscriptionPlanUpdate {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the Subscription entity.
func (_u *SubscriptionPlanUpdate) AddSubscriptions(v ...*Subscription) *SubscriptionPlanUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// Mutation returns the SubscriptionPlanMutation object of the builder.
func (_u *SubscriptionPlanUpdate) Mutation() *SubscriptionPlanMutation {
	return _u.mutation
}

// ClearSubscriptions clears all "subscriptions" edges to the Subscription entity.
func (_u *SubscriptionPlanUpdate) ClearSubscriptions() *SubscriptionPlanUpdate {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to Subscription entities by IDs.
func (_u *SubscriptionPlanUpdate) RemoveSubscriptionIDs(ids ...string) *SubscriptionPlanUpdate {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to Subscription entities.
func (_u *SubscriptionPlanUpdate) RemoveSubscriptions(v ...*Subscription) *SubscriptionPlanUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionPlanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionPlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionPlanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SubscriptionPlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscriptionplan.Table, subscriptionplan.Columns, sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(subscriptionplan.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(subscriptionplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(subscriptionplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalCredits(); ok {
		_spec.SetField(subscriptionplan.FieldTotalCredits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCredits(); ok {
		_spec.AddField(subscriptionplan.FieldTotalCredits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidityDuration(); ok {
		_spec.SetField(subscriptionplan.FieldValidityDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDuration(); ok {
		_spec.AddField(subscriptionplan.FieldValidityDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidityUnit(); ok {
		_spec.SetField(subscriptionplan.FieldValidityUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreditResetCycle(); ok {
		_spec.SetField(subscriptionplan.FieldCreditResetCycle, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(subscriptionplan.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionplan.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.SubscriptionsTable,
			Columns: []string{subscriptionplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.SubscriptionsTable,
			Columns: []string{subscriptionplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.SubscriptionsTable,
			Columns: []string{subscriptionplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionPlanUpdateOne is the builder for updating a single SubscriptionPlan entity.
type SubscriptionPlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionPlanMutation
}

// SetTitle sets the "title" field.
func (_u *SubscriptionPlanUpdateOne) SetTitle(v string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableTitle(v *string) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *SubscriptionPlanUpdateOne) SetPrice(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillablePrice(v *float64) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *SubscriptionPlanUpdateOne) AddPrice(v float64) *SubscriptionPlanUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetTotalCredits sets the "totalCredits" field.
func (_u *SubscriptionPlanUpdateOne) SetTotalCredits(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetTotalCredits()
	_u.mutation.SetTotalCredits(v)
	return _u
}

// SetNillableTotalCredits sets the "totalCredits" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableTotalCredits(v *int) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetTotalCredits(*v)
	}
	return _u
}

// AddTotalCredits adds value to the "totalCredits" field.
func (_u *SubscriptionPlanUpdateOne) AddTotalCredits(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.AddTotalCredits(v)
	return _u
}

// SetSortOrder sets the "sortOrder" field.
func (_u *SubscriptionPlanUpdateOne) SetSortOrder(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sortOrder" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableSortOrder(v *int) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sortOrder" field.
func (_u *SubscriptionPlanUpdateOne) AddSortOrder(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetValidityDuration sets the "validityDuration" field.
func (_u *SubscriptionPlanUpdateOne) SetValidityDuration(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.ResetValidityDuration()
	_u.mutation.SetValidityDuration(v)
	return _u
}

// SetNillableValidityDuration sets the "validityDuration" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableValidityDuration(v *int) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetValidityDuration(*v)
	}
	return _u
}

// AddValidityDuration adds value to the "validityDuration" field.
func (_u *SubscriptionPlanUpdateOne) AddValidityDuration(v int) *SubscriptionPlanUpdateOne {
	_u.mutation.AddValidityDuration(v)
	return _u
}

// SetValidityUnit sets the "validityUnit" field.
func (_u *SubscriptionPlanUpdateOne) SetValidityUnit(v string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetValidityUnit(v)
	return _u
}

// SetNillableValidityUnit sets the "validityUnit" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableValidityUnit(v *string) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetValidityUnit(*v)
	}
	return _u
}

// SetCreditResetCycle sets the "creditResetCycle" field.
func (_u *SubscriptionPlanUpdateOne) SetCreditResetCycle(v string) *SubscriptionPlanUpdateOne {
	_u.mutation.SetCreditResetCycle(v)
	return _u
}

// SetNillableCreditResetCycle sets the "creditResetCycle" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableCreditResetCycle(v *string) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetCreditResetCycle(*v)
	}
	return _u
}

// SetIsActive sets the "isActive" field.
func (_u *SubscriptionPlanUpdateOne) SetIsActive(v bool) *SubscriptionPlanUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "isActive" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableIsActive(v *bool) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *SubscriptionPlanUpdateOne) SetCreatedAt(v time.Time) *SubscriptionPlanUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *SubscriptionPlanUpdateOne) SetNillableCreatedAt(v *time.Time) *SubscriptionPlanUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *SubscriptionPlanUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionPlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddSubscriptionIDs adds the "subscriptions" edge to the Subscription entity by IDs.
func (_u *SubscriptionPlanUpdateOne) AddSubscriptionIDs(ids ...string) *SubscriptionPlanUpdateOne {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the Subscription entity.
func (_u *SubscriptionPlanUpdateOne) AddSubscriptions(v ...*Subscription) *SubscriptionPlanUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// Mutation returns the SubscriptionPlanMutation object of the builder.
func (_u *SubscriptionPlanUpdateOne) Mutation() *SubscriptionPlanMutation {
	return _u.mutation
}

// ClearSubscriptions clears all "subscriptions" edges to the Subscription entity.
func (_u *SubscriptionPlanUpdateOne) ClearSubscriptions() *SubscriptionPlanUpdateOne {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to Subscription entities by IDs.
func (_u *SubscriptionPlanUpdateOne) RemoveSubscriptionIDs(ids ...string) *SubscriptionPlanUpdateOne {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to Subscription entities.
func (_u *SubscriptionPlanUpdateOne) RemoveSubscriptions(v ...*Subscription) *SubscriptionPlanUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// Where appends a list predicates to the SubscriptionPlanUpdate builder.
func (_u *SubscriptionPlanUpdateOne) Where(ps ...predicate.SubscriptionPlan) *SubscriptionPlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionPlanUpdateOne) Select(field string, fields ...string) *SubscriptionPlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionPlan entity.
func (_u *SubscriptionPlanUpdateOne) Save(ctx context.Context) (*SubscriptionPlan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPlanUpdateOne) SaveX(ctx context.Context) *SubscriptionPlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionPlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionPlanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SubscriptionPlanUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionPlan, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscriptionplan.Table, subscriptionplan.Columns, sqlgraph.NewFieldSpec(subscriptionplan.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionPlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionplan.FieldID)
		for _, f := range fields {
			if !subscriptionplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(subscriptionplan.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(subscriptionplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(subscriptionplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.TotalCredits(); ok {
		_spec.SetField(subscriptionplan.FieldTotalCredits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCredits(); ok {
		_spec.AddField(subscriptionplan.FieldTotalCredits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(subscriptionplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidityDuration(); ok {
		_spec.SetField(subscriptionplan.FieldValidityDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDuration(); ok {
		_spec.AddField(subscriptionplan.FieldValidityDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValidityUnit(); ok {
		_spec.SetField(subscriptionplan.FieldValidityUnit, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreditResetCycle(); ok {
		_spec.SetField(subscriptionplan.FieldCreditResetCycle, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(subscriptionplan.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionplan.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.SubscriptionsTable,
			Columns: []string{subscriptionplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.SubscriptionsTable,
			Columns: []string{subscriptionplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscriptionplan.SubscriptionsTable,
			Columns: []string{subscriptionplan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SubscriptionPlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
