// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountColumns holds the columns for the "Account" table.
	AccountColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "provider", Type: field.TypeString},
		{Name: "providerAccountId", Type: field.TypeString},
		{Name: "access_token", Type: field.TypeString, Nullable: true},
		{Name: "refresh_token", Type: field.TypeString, Nullable: true},
		{Name: "expires_at", Type: field.TypeInt, Nullable: true},
		{Name: "token_type", Type: field.TypeString, Nullable: true},
		{Name: "scope", Type: field.TypeString, Nullable: true},
		{Name: "id_token", Type: field.TypeString, Nullable: true},
		{Name: "session_state", Type: field.TypeString, Nullable: true},
		{Name: "createdAt", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "userId", Type: field.TypeString},
	}
	// AccountTable holds the schema information for the "Account" table.
	AccountTable = &schema.Table{
		Name:       "Account",
		Columns:    AccountColumns,
		PrimaryKey: []*schema.Column{AccountColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "Account_userId_fkey",
				Columns:    []*schema.Column{AccountColumns[12]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "Account_provider_providerAccountId_key",
				Unique:  true,
				Columns: []*schema.Column{AccountColumns[1], AccountColumns[2]},
			},
			{
				Name:    "Account_userId_idx",
				Unique:  false,
				Columns: []*schema.Column{AccountColumns[12]},
			},
		},
	}
	// AdvertisementColumns holds the columns for the "Advertisement" table.
	AdvertisementColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "image", Type: field.TypeString},
		{Name: "imageWidth", Type: field.TypeInt},
		{Name: "imageHeight", Type: field.TypeInt},
		{Name: "link", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "position", Type: field.TypeString},
		{Name: "isActive", Type: field.TypeBool, Default: true},
		{Name: "createdAt", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updatedAt", Type: field.TypeTime},
	}
	// AdvertisementTable holds the schema information for the "Advertisement" table.
	AdvertisementTable = &schema.Table{
		Name:       "Advertisement",
		Columns:    AdvertisementColumns,
		PrimaryKey: []*schema.Column{AdvertisementColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "Advertisement_position_key",
				Unique:  true,
				Columns: []*schema.Column{AdvertisementColumns[6]},
			},
			{
				Name:    "Advertisement_position_idx",
				Unique:  false,
				Columns: []*schema.Column{AdvertisementColumns[6]},
			},
			{
				Name:    "Advertisement_isActive_idx",
				Unique:  false,
				Columns: []*schema.Column{AdvertisementColumns[7]},
			},
		},
	}
	// APIColumns holds the columns for the "Api" table.
	APIColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "alias", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "endpoint", Type: field.TypeString},
		{Name: "method", Type: field.TypeString},
		{Name: "pricing", Type: field.TypeInt, Default: 0},
		{Name: "documentation", Type: field.TypeString, Nullable: true},
		{Name: "preScript", Type: field.TypeString, Nullable: true},
		{Name: "postScript", Type: field.TypeString, Nullable: true},
		{Name: "isActive", Type: field.TypeBool, Default: true},
		{Name: "callCount", Type: field.TypeInt, Default: 0},
		{Name: "createdAt", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "categoryId", Type: field.TypeString},
	}
	// APITable holds the schema information for the "Api" table.
	APITable = &schema.Table{
		Name:       "Api",
		Columns:    APIColumns,
		PrimaryKey: []*schema.Column{APIColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "Api_categoryId_fkey",
				Columns:    []*schema.Column{APIColumns[14]},
				RefColumns: []*schema.Column{ApiCategoryColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "Api_alias_key",
				Unique:  true,
				Columns: []*schema.Column{APIColumns[2]},
			},
			{
				Name:    "Api_endpoint_key",
				Unique:  true,
				Columns: []*schema.Column{APIColumns[4]},
			},
		},
	}
	// ApiCategoryColumns holds the columns for the "ApiCategory" table.
	ApiCategoryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "icon", Type: field.TypeString, Nullable: true},
	}
	// ApiCategoryTable holds the schema information for the "ApiCategory" table.
	ApiCategoryTable = &schema.Table{
		Name:       "ApiCategory",
		Columns:    ApiCategoryColumns,
		PrimaryKey: []*schema.Column{ApiCategoryColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ApiCategory_name_key",
				Unique:  true,
				Columns: []*schema.Column{ApiCategoryColumns[1]},
			},
		},
	}
	// ApiParameterColumns holds the columns for the "ApiParameter" table.
	ApiParameterColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "required", Type: field.TypeBool},
		{Name: "description", Type: field.TypeString},
		{Name: "defaultValue", Type: field.TypeString, Nullable: true},
		{Name: "apiId", Type: field.TypeString},
	}
	// ApiParameterTable holds the schema information for the "ApiParameter" table.
	ApiParameterTable = &schema.Table{
		Name:       "ApiParameter",
		Columns:    ApiParameterColumns,
		PrimaryKey: []*schema.Column{ApiParameterColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ApiParameter_apiId_fkey",
				Columns:    []*schema.Column{ApiParameterColumns[6]},
				RefColumns: []*schema.Column{APIColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
	}
	// ApiResponseColumns holds the columns for the "ApiResponse" table.
	ApiResponseColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "apiId", Type: field.TypeString},
	}
	// ApiResponseTable holds the schema information for the "ApiResponse" table.
	ApiResponseTable = &schema.Table{
		Name:       "ApiResponse",
		Columns:    ApiResponseColumns,
		PrimaryKey: []*schema.Column{ApiResponseColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ApiResponse_apiId_fkey",
				Columns:    []*schema.Column{ApiResponseColumns[4]},
				RefColumns: []*schema.Column{APIColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
	}
	// ApiTokenColumns holds the columns for the "ApiToken" table.
	ApiTokenColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "token", Type: field.TypeString},
		{Name: "permissions", Type: field.TypeString},
		{Name: "lastUsedAt", Type: field.TypeTime, Nullable: true},
		{Name: "expiresAt", Type: field.TypeTime, Nullable: true},
		{Name: "isActive", Type: field.TypeBool, Default: true},
		{Name: "createdAt", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "userId", Type: field.TypeString},
	}
	// ApiTokenTable holds the schema information for the "ApiToken" table.
	ApiTokenTable = &schema.Table{
		Name:       "ApiToken",
		Columns:    ApiTokenColumns,
		PrimaryKey: []*schema.Column{ApiTokenColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ApiToken_userId_fkey",
				Columns:    []*schema.Column{ApiTokenColumns[9]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "ApiToken_token_key",
				Unique:  true,
				Columns: []*schema.Column{ApiTokenColumns[2]},
			},
			{
				Name:    "ApiToken_userId_idx",
				Unique:  false,
				Columns: []*schema.Column{ApiTokenColumns[9]},
			},
			{
				Name:    "ApiToken_token_idx",
				Unique:  false,
				Columns: []*schema.Column{ApiTokenColumns[2]},
			},
		},
	}
	// ApiUsageColumns holds the columns for the "ApiUsage" table.
	ApiUsageColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "credits", Type: field.TypeInt},
		{Name: "status", Type: field.TypeString},
		{Name: "createdAt", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "apiId", Type: field.TypeString},
		{Name: "userId", Type: field.TypeString},
	}
	// ApiUsageTable holds the schema information for the "ApiUsage" table.
	ApiUsageTable = &schema.Table{
		Name:       "ApiUsage",
		Columns:    ApiUsageColumns,
		PrimaryKey: []*schema.Column{ApiUsageColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ApiUsage_apiId_fkey",
				Columns:    []*schema.Column{ApiUsageColumns[4]},
				RefColumns: []*schema.Column{APIColumns[0]},
				OnDelete:   schema.Restrict,
			},
			{
				Symbol:     "ApiUsage_userId_fkey",
				Columns:    []*schema.Column{ApiUsageColumns[5]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
	}
	// AuditLogColumns holds the columns for the "AuditLog" table.
	AuditLogColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "resource", Type: field.TypeString},
		{Name: "details", Type: field.TypeString, Nullable: true},
		{Name: "ipAddress", Type: field.TypeString, Nullable: true},
		{Name: "userAgent", Type: field.TypeString, Nullable: true},
		{Name: "level", Type: field.TypeString, Default: "info"},
		{Name: "status", Type: field.TypeString, Default: "success"},
		{Name: "metadata", Type: field.TypeString, Nullable: true},
		{Name: "createdAt", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "userId", Type: field.TypeString, Nullable: true},
	}
	// AuditLogTable holds the schema information for the "AuditLog" table.
	AuditLogTable = &schema.Table{
		Name:       "AuditLog",
		Columns:    AuditLogColumns,
		PrimaryKey: []*schema.Column{AuditLogColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "AuditLog_userId_fkey",
				Columns:    []*schema.Column{AuditLogColumns[10]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "AuditLog_userId_idx",
				Unique:  false,
				Columns: []*schema.Column{AuditLogColumns[10]},
			},
			{
				Name:    "AuditLog_level_idx",
				Unique:  false,
				Columns: []*schema.Column{AuditLogColumns[6]},
			},
			{
				Name:    "AuditLog_status_idx",
				Unique:  false,
				Columns: []*schema.Column{AuditLogColumns[7]},
			},
			{
				Name:    "AuditLog_createdAt_idx",
				Unique:  false,
				Columns: []*schema.Column{AuditLogColumns[9]},
			},
		},
	}
	// McpServiceColumns holds the columns for the "McpService" table.
	McpServiceColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "identifier", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "documentation", Type: field.TypeString, Nullable: true},
		{Name: "type", Type: field.TypeString},
		{Name: "command", Type: field.TypeString, Nullable: true},
		{Name: "endpoint", Type: field.TypeString, Nullable: true},
		{Name: "envVars", Type: field.TypeString, Nullable: true},
		{Name: "pricing", Type: field.TypeInt, Default: 0},
		{Name: "isActive", Type: field.TypeBool, Default: true},
		{Name: "callCount", Type: field.TypeInt, Default: 0},
		{Name: "createdAt", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "categoryId", Type: field.TypeString, Nullable: true},
	}
	// McpServiceTable holds the schema information for the "McpService" table.
	McpServiceTable = &schema.Table{
		Name:       "McpService",
		Columns:    McpServiceColumns,
		PrimaryKey: []*schema.Column{McpServiceColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "McpService_categoryId_fkey",
				Columns:    []*schema.Column{McpServiceColumns[14]},
				RefColumns: []*schema.Column{ApiCategoryColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "McpService_identifier_key",
				Unique:  true,
				Columns: []*schema.Column{McpServiceColumns[2]},
			},
			{
				Name:    "McpService_categoryId_idx",
				Unique:  false,
				Columns: []*schema.Column{McpServiceColumns[14]},
			},
			{
				Name:    "McpService_type_idx",
				Unique:  false,
				Columns: []*schema.Column{McpServiceColumns[5]},
			},
			{
				Name:    "McpService_isActive_idx",
				Unique:  false,
				Columns: []*schema.Column{McpServiceColumns[10]},
			},
		},
	}
	// McpUsageColumns holds the columns for the "McpUsage" table.
	McpUsageColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "credits", Type: field.TypeInt},
		{Name: "status", Type: field.TypeString},
		{Name: "createdAt", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "mcpId", Type: field.TypeString},
		{Name: "userId", Type: field.TypeString},
	}
	// McpUsageTable holds the schema information for the "McpUsage" table.
	McpUsageTable = &schema.Table{
		Name:       "McpUsage",
		Columns:    McpUsageColumns,
		PrimaryKey: []*schema.Column{McpUsageColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "McpUsage_mcpId_fkey",
				Columns:    []*schema.Column{McpUsageColumns[4]},
				RefColumns: []*schema.Column{McpServiceColumns[0]},
				OnDelete:   schema.Restrict,
			},
			{
				Symbol:     "McpUsage_userId_fkey",
				Columns:    []*schema.Column{McpUsageColumns[5]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "McpUsage_userId_idx",
				Unique:  false,
				Columns: []*schema.Column{McpUsageColumns[5]},
			},
			{
				Name:    "McpUsage_mcpId_idx",
				Unique:  false,
				Columns: []*schema.Column{McpUsageColumns[4]},
			},
		},
	}
	// PaymentColumns holds the columns for the "Payment" table.
	PaymentColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "outTradeNo", Type: field.TypeString},
		{Name: "transactionId", Type: field.TypeString, Nullable: true},
		{Name: "method", Type: field.TypeString},
		{Name: "amount", Type: field.TypeFloat64},
		{Name: "currency", Type: field.TypeString, Default: "CNY"},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "qrcodeUrl", Type: field.TypeString, Nullable: true},
		{Name: "payUrl", Type: field.TypeString, Nullable: true},
		{Name: "notifyUrl", Type: field.TypeString, Nullable: true},
		{Name: "paidAt", Type: field.TypeTime, Nullable: true},
		{Name: "expiredAt", Type: field.TypeTime, Nullable: true},
		{Name: "cancelledAt", Type: field.TypeTime, Nullable: true},
		{Name: "metadata", Type: field.TypeString, Nullable: true},
		{Name: "callbackVersion", Type: field.TypeInt, Default: 0},
		{Name: "callbackKey", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "callbackProcessedAt", Type: field.TypeTime, Nullable: true},
		{Name: "createdAt", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "userId", Type: field.TypeString},
	}
	// PaymentTable holds the schema information for the "Payment" table.
	PaymentTable = &schema.Table{
		Name:       "Payment",
		Columns:    PaymentColumns,
		PrimaryKey: []*schema.Column{PaymentColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "Payment_userId_fkey",
				Columns:    []*schema.Column{PaymentColumns[19]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "Payment_outTradeNo_key",
				Unique:  true,
				Columns: []*schema.Column{PaymentColumns[1]},
			},
			{
				Name:    "Payment_userId_idx",
				Unique:  false,
				Columns: []*schema.Column{PaymentColumns[19]},
			},
			{
				Name:    "Payment_status_idx",
				Unique:  false,
				Columns: []*schema.Column{PaymentColumns[6]},
			},
			{
				Name:    "Payment_method_idx",
				Unique:  false,
				Columns: []*schema.Column{PaymentColumns[3]},
			},
			{
				Name:    "Payment_outTradeNo_idx",
				Unique:  false,
				Columns: []*schema.Column{PaymentColumns[1]},
			},
			{
				Name:    "Payment_transactionId_idx",
				Unique:  false,
				Columns: []*schema.Column{PaymentColumns[2]},
			},
			{
				Name:    "Payment_callbackVersion_idx",
				Unique:  false,
				Columns: []*schema.Column{PaymentColumns[14]},
			},
			{
				Name:    "Payment_createdAt_idx",
				Unique:  false,
				Columns: []*schema.Column{PaymentColumns[17]},
			},
		},
	}
	// RedemptionCodeColumns holds the columns for the "RedemptionCode" table.
	RedemptionCodeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "code", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "planId", Type: field.TypeString, Nullable: true},
		{Name: "planName", Type: field.TypeString, Nullable: true},
		{Name: "credits", Type: field.TypeInt, Nullable: true},
		{Name: "expiresAt", Type: field.TypeTime, Nullable: true},
		{Name: "isUsed", Type: field.TypeBool, Default: false},
		{Name: "usedBy", Type: field.TypeString, Nullable: true},
		{Name: "usedAt", Type: field.TypeTime, Nullable: true},
		{Name: "createdBy", Type: field.TypeString},
		{Name: "batchId", Type: field.TypeString, Nullable: true},
		{Name: "createdAt", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updatedAt", Type: field.TypeTime},
	}
	// RedemptionCodeTable holds the schema information for the "RedemptionCode" table.
	RedemptionCodeTable = &schema.Table{
		Name:       "RedemptionCode",
		Columns:    RedemptionCodeColumns,
		PrimaryKey: []*schema.Column{RedemptionCodeColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "RedemptionCode_code_key",
				Unique:  true,
				Columns: []*schema.Column{RedemptionCodeColumns[1]},
			},
			{
				Name:    "RedemptionCode_code_idx",
				Unique:  false,
				Columns: []*schema.Column{RedemptionCodeColumns[1]},
			},
			{
				Name:    "RedemptionCode_type_idx",
				Unique:  false,
				Columns: []*schema.Column{RedemptionCodeColumns[2]},
			},
			{
				Name:    "RedemptionCode_isUsed_idx",
				Unique:  false,
				Columns: []*schema.Column{RedemptionCodeColumns[7]},
			},
			{
				Name:    "RedemptionCode_batchId_idx",
				Unique:  false,
				Columns: []*schema.Column{RedemptionCodeColumns[11]},
			},
			{
				Name:    "RedemptionCode_createdBy_idx",
				Unique:  false,
				Columns: []*schema.Column{RedemptionCodeColumns[10]},
			},
		},
	}
	// ScheduledJobColumns holds the columns for the "ScheduledJob" table.
	ScheduledJobColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "taskKey", Type: field.TypeString},
		{Name: "scheduleType", Type: field.TypeString},
		{Name: "expression", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "lastRunAt", Type: field.TypeTime, Nullable: true},
		{Name: "lastStatus", Type: field.TypeString, Default: "never"},
		{Name: "lastError", Type: field.TypeString, Nullable: true},
		{Name: "createdAt", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updatedAt", Type: field.TypeTime},
	}
	// ScheduledJobTable holds the schema information for the "ScheduledJob" table.
	ScheduledJobTable = &schema.Table{
		Name:       "ScheduledJob",
		Columns:    ScheduledJobColumns,
		PrimaryKey: []*schema.Column{ScheduledJobColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ScheduledJob_taskKey_key",
				Unique:  true,
				Columns: []*schema.Column{ScheduledJobColumns[2]},
			},
			{
				Name:    "ScheduledJob_enabled_idx",
				Unique:  false,
				Columns: []*schema.Column{ScheduledJobColumns[5]},
			},
		},
	}
	// SessionColumns holds the columns for the "Session" table.
	SessionColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "sessionToken", Type: field.TypeString},
		{Name: "expires", Type: field.TypeTime},
		{Name: "createdAt", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "userId", Type: field.TypeString},
	}
	// SessionTable holds the schema information for the "Session" table.
	SessionTable = &schema.Table{
		Name:       "Session",
		Columns:    SessionColumns,
		PrimaryKey: []*schema.Column{SessionColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "Session_userId_fkey",
				Columns:    []*schema.Column{SessionColumns[5]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "Session_sessionToken_key",
				Unique:  true,
				Columns: []*schema.Column{SessionColumns[1]},
			},
		},
	}
	// SubscriptionColumns holds the columns for the "Subscription" table.
	SubscriptionColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "planName", Type: field.TypeString},
		{Name: "credits", Type: field.TypeInt},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "startDate", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "endDate", Type: field.TypeTime},
		{Name: "isActive", Type: field.TypeBool, Default: true},
		{Name: "createdAt", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "paymentId", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "planId", Type: field.TypeString, Nullable: true},
		{Name: "userId", Type: field.TypeString},
	}
	// SubscriptionTable holds the schema information for the "Subscription" table.
	SubscriptionTable = &schema.Table{
		Name:       "Subscription",
		Columns:    SubscriptionColumns,
		PrimaryKey: []*schema.Column{SubscriptionColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "Subscription_paymentId_fkey",
				Columns:    []*schema.Column{SubscriptionColumns[9]},
				RefColumns: []*schema.Column{PaymentColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "Subscription_planId_fkey",
				Columns:    []*schema.Column{SubscriptionColumns[10]},
				RefColumns: []*schema.Column{SubscriptionPlanColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "Subscription_userId_fkey",
				Columns:    []*schema.Column{SubscriptionColumns[11]},
				RefColumns: []*schema.Column{UserColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "Subscription_userId_idx",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionColumns[11]},
			},
			{
				Name:    "Subscription_planId_idx",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionColumns[10]},
			},
			{
				Name:    "Subscription_isActive_idx",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionColumns[6]},
			},
			{
				Name:    "Subscription_paymentId_idx",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionColumns[9]},
			},
		},
	}
	// SubscriptionPlanColumns holds the columns for the "SubscriptionPlan" table.
	SubscriptionPlanColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "totalCredits", Type: field.TypeInt},
		{Name: "sortOrder", Type: field.TypeInt, Default: 0},
		{Name: "validityDuration", Type: field.TypeInt},
		{Name: "validityUnit", Type: field.TypeString, Default: "day"},
		{Name: "creditResetCycle", Type: field.TypeString, Default: "month"},
		{Name: "isActive", Type: field.TypeBool, Default: true},
		{Name: "createdAt", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updatedAt", Type: field.TypeTime},
	}
	// SubscriptionPlanTable holds the schema information for the "SubscriptionPlan" table.
	SubscriptionPlanTable = &schema.Table{
		Name:       "SubscriptionPlan",
		Columns:    SubscriptionPlanColumns,
		PrimaryKey: []*schema.Column{SubscriptionPlanColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "SubscriptionPlan_title_key",
				Unique:  true,
				Columns: []*schema.Column{SubscriptionPlanColumns[1]},
			},
			{
				Name:    "SubscriptionPlan_sortOrder_idx",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionPlanColumns[4]},
			},
			{
				Name:    "SubscriptionPlan_isActive_idx",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionPlanColumns[8]},
			},
		},
	}
	// SystemSettingColumns holds the columns for the "SystemSetting" table.
	SystemSettingColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString},
		{Name: "category", Type: field.TypeString, Default: "general"},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "createdAt", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updatedAt", Type: field.TypeTime},
	}
	// SystemSettingTable holds the schema information for the "SystemSetting" table.
	SystemSettingTable = &schema.Table{
		Name:       "SystemSetting",
		Columns:    SystemSettingColumns,
		PrimaryKey: []*schema.Column{SystemSettingColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "SystemSetting_key_key",
				Unique:  true,
				Columns: []*schema.Column{SystemSettingColumns[1]},
			},
			{
				Name:    "SystemSetting_key_idx",
				Unique:  false,
				Columns: []*schema.Column{SystemSettingColumns[1]},
			},
			{
				Name:    "SystemSetting_category_idx",
				Unique:  false,
				Columns: []*schema.Column{SystemSettingColumns[3]},
			},
		},
	}
	// UserColumns holds the columns for the "User" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString},
		{Name: "emailVerified", Type: field.TypeTime, Nullable: true},
		{Name: "image", Type: field.TypeString, Nullable: true},
		{Name: "username", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "role", Type: field.TypeString, Default: "user"},
		{Name: "credits", Type: field.TypeInt, Default: 1000},
		{Name: "createdAt", Type: field.TypeTime, Default: "CURRENT_TIMESTAMP"},
		{Name: "updatedAt", Type: field.TypeTime},
	}
	// UserTable holds the schema information for the "User" table.
	UserTable = &schema.Table{
		Name:       "User",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "User_email_key",
				Unique:  true,
				Columns: []*schema.Column{UserColumns[2]},
			},
			{
				Name:    "User_username_key",
				Unique:  true,
				Columns: []*schema.Column{UserColumns[5]},
			},
		},
	}
	// VerificationTokenColumns holds the columns for the "VerificationToken" table.
	VerificationTokenColumns = []*schema.Column{
		{Name: "identifier", Type: field.TypeString},
		{Name: "token", Type: field.TypeString},
		{Name: "expires", Type: field.TypeTime},
	}
	// VerificationTokenTable holds the schema information for the "VerificationToken" table.
	VerificationTokenTable = &schema.Table{
		Name:       "VerificationToken",
		Columns:    VerificationTokenColumns,
		PrimaryKey: []*schema.Column{VerificationTokenColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "VerificationToken_identifier_token_key",
				Unique:  true,
				Columns: []*schema.Column{VerificationTokenColumns[0], VerificationTokenColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountTable,
		AdvertisementTable,
		APITable,
		ApiCategoryTable,
		ApiParameterTable,
		ApiResponseTable,
		ApiTokenTable,
		ApiUsageTable,
		AuditLogTable,
		McpServiceTable,
		McpUsageTable,
		PaymentTable,
		RedemptionCodeTable,
		ScheduledJobTable,
		SessionTable,
		SubscriptionTable,
		SubscriptionPlanTable,
		SystemSettingTable,
		UserTable,
		VerificationTokenTable,
	}
)

func init() {
	AccountTable.ForeignKeys[0].RefTable = UserTable
	AccountTable.Annotation = &entsql.Annotation{
		Table: "Account",
	}
	AdvertisementTable.Annotation = &entsql.Annotation{
		Table: "Advertisement",
	}
	APITable.ForeignKeys[0].RefTable = ApiCategoryTable
	APITable.Annotation = &entsql.Annotation{
		Table: "Api",
	}
	ApiCategoryTable.Annotation = &entsql.Annotation{
		Table: "ApiCategory",
	}
	ApiParameterTable.ForeignKeys[0].RefTable = APITable
	ApiParameterTable.Annotation = &entsql.Annotation{
		Table: "ApiParameter",
	}
	ApiResponseTable.ForeignKeys[0].RefTable = APITable
	ApiResponseTable.Annotation = &entsql.Annotation{
		Table: "ApiResponse",
	}
	ApiTokenTable.ForeignKeys[0].RefTable = UserTable
	ApiTokenTable.Annotation = &entsql.Annotation{
		Table: "ApiToken",
	}
	ApiUsageTable.ForeignKeys[0].RefTable = APITable
	ApiUsageTable.ForeignKeys[1].RefTable = UserTable
	ApiUsageTable.Annotation = &entsql.Annotation{
		Table: "ApiUsage",
	}
	AuditLogTable.ForeignKeys[0].RefTable = UserTable
	AuditLogTable.Annotation = &entsql.Annotation{
		Table: "AuditLog",
	}
	McpServiceTable.ForeignKeys[0].RefTable = ApiCategoryTable
	McpServiceTable.Annotation = &entsql.Annotation{
		Table: "McpService",
	}
	McpUsageTable.ForeignKeys[0].RefTable = McpServiceTable
	McpUsageTable.ForeignKeys[1].RefTable = UserTable
	McpUsageTable.Annotation = &entsql.Annotation{
		Table: "McpUsage",
	}
	PaymentTable.ForeignKeys[0].RefTable = UserTable
	PaymentTable.Annotation = &entsql.Annotation{
		Table: "Payment",
	}
	RedemptionCodeTable.Annotation = &entsql.Annotation{
		Table: "RedemptionCode",
	}
	ScheduledJobTable.Annotation = &entsql.Annotation{
		Table: "ScheduledJob",
	}
	SessionTable.ForeignKeys[0].RefTable = UserTable
	SessionTable.Annotation = &entsql.Annotation{
		Table: "Session",
	}
	SubscriptionTable.ForeignKeys[0].RefTable = PaymentTable
	SubscriptionTable.ForeignKeys[1].RefTable = SubscriptionPlanTable
	SubscriptionTable.ForeignKeys[2].RefTable = UserTable
	SubscriptionTable.Annotation = &entsql.Annotation{
		Table: "Subscription",
	}
	SubscriptionPlanTable.Annotation = &entsql.Annotation{
		Table: "SubscriptionPlan",
	}
	SystemSettingTable.Annotation = &entsql.Annotation{
		Table: "SystemSetting",
	}
	UserTable.Annotation = &entsql.Annotation{
		Table: "User",
	}
	VerificationTokenTable.Annotation = &entsql.Annotation{
		Table: "VerificationToken",
	}
}
