// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/nex-api/ent/account"
	"github.com/shuTwT/nex-api/ent/predicate"
	"github.com/shuTwT/nex-api/ent/user"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserId sets the "userId" field.
func (_u *AccountUpdate) SetUserId(v string) *AccountUpdate {
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableUserId(v *string) *AccountUpdate {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AccountUpdate) SetProvider(v string) *AccountUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableProvider(v *string) *AccountUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderAccountId sets the "providerAccountId" field.
func (_u *AccountUpdate) SetProviderAccountId(v string) *AccountUpdate {
	_u.mutation.SetProviderAccountId(v)
	return _u
}

// SetNillableProviderAccountId sets the "providerAccountId" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableProviderAccountId(v *string) *AccountUpdate {
	if v != nil {
		_u.SetProviderAccountId(*v)
	}
	return _u
}

// SetAccessToken sets the "accessToken" field.
func (_u *AccountUpdate) SetAccessToken(v string) *AccountUpdate {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "accessToken" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableAccessToken(v *string) *AccountUpdate {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// ClearAccessToken clears the value of the "accessToken" field.
func (_u *AccountUpdate) ClearAccessToken() *AccountUpdate {
	_u.mutation.ClearAccessToken()
	return _u
}

// SetRefreshToken sets the "refreshToken" field.
func (_u *AccountUpdate) SetRefreshToken(v string) *AccountUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refreshToken" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableRefreshToken(v *string) *AccountUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refreshToken" field.
func (_u *AccountUpdate) ClearRefreshToken() *AccountUpdate {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetExpiresAt sets the "expiresAt" field.
func (_u *AccountUpdate) SetExpiresAt(v int) *AccountUpdate {
	_u.mutation.ResetExpiresAt()
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expiresAt" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableExpiresAt(v *int) *AccountUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// AddExpiresAt adds value to the "expiresAt" field.
func (_u *AccountUpdate) AddExpiresAt(v int) *AccountUpdate {
	_u.mutation.AddExpiresAt(v)
	return _u
}

// ClearExpiresAt clears the value of the "expiresAt" field.
func (_u *AccountUpdate) ClearExpiresAt() *AccountUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetTokenType sets the "tokenType" field.
func (_u *AccountUpdate) SetTokenType(v string) *AccountUpdate {
	_u.mutation.SetTokenType(v)
	return _u
}

// SetNillableTokenType sets the "tokenType" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableTokenType(v *string) *AccountUpdate {
	if v != nil {
		_u.SetTokenType(*v)
	}
	return _u
}

// ClearTokenType clears the value of the "tokenType" field.
func (_u *AccountUpdate) ClearTokenType() *AccountUpdate {
	_u.mutation.ClearTokenType()
	return _u
}

// SetScope sets the "scope" field.
func (_u *AccountUpdate) SetScope(v string) *AccountUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableScope(v *string) *AccountUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// ClearScope clears the value of the "scope" field.
func (_u *AccountUpdate) ClearScope() *AccountUpdate {
	_u.mutation.ClearScope()
	return _u
}

// SetIdToken sets the "idToken" field.
func (_u *AccountUpdate) SetIdToken(v string) *AccountUpdate {
	_u.mutation.SetIdToken(v)
	return _u
}

// SetNillableIdToken sets the "idToken" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableIdToken(v *string) *AccountUpdate {
	if v != nil {
		_u.SetIdToken(*v)
	}
	return _u
}

// ClearIdToken clears the value of the "idToken" field.
func (_u *AccountUpdate) ClearIdToken() *AccountUpdate {
	_u.mutation.ClearIdToken()
	return _u
}

// SetSessionState sets the "sessionState" field.
func (_u *AccountUpdate) SetSessionState(v string) *AccountUpdate {
	_u.mutation.SetSessionState(v)
	return _u
}

// SetNillableSessionState sets the "sessionState" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableSessionState(v *string) *AccountUpdate {
	if v != nil {
		_u.SetSessionState(*v)
	}
	return _u
}

// ClearSessionState clears the value of the "sessionState" field.
func (_u *AccountUpdate) ClearSessionState() *AccountUpdate {
	_u.mutation.ClearSessionState()
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *AccountUpdate) SetCreatedAt(v time.Time) *AccountUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *AccountUpdate) SetNillableCreatedAt(v *time.Time) *AccountUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *AccountUpdate) SetUpdatedAt(v time.Time) *AccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AccountUpdate) SetUserID(id string) *AccountUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccountUpdate) SetUser(v *User) *AccountUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdate) Mutation() *AccountMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccountUpdate) ClearUser() *AccountUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := account.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Account.user"`)
	}
	return nil
}

func (_u *AccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(account.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderAccountId(); ok {
		_spec.SetField(account.FieldProviderAccountId, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(account.FieldAccessToken, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCleared() {
		_spec.ClearField(account.FieldAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(account.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(account.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(account.FieldExpiresAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExpiresAt(); ok {
		_spec.AddField(account.FieldExpiresAt, field.TypeInt, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(account.FieldExpiresAt, field.TypeInt)
	}
	if value, ok := _u.mutation.TokenType(); ok {
		_spec.SetField(account.FieldTokenType, field.TypeString, value)
	}
	if _u.mutation.TokenTypeCleared() {
		_spec.ClearField(account.FieldTokenType, field.TypeString)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(account.FieldScope, field.TypeString, value)
	}
	if _u.mutation.ScopeCleared() {
		_spec.ClearField(account.FieldScope, field.TypeString)
	}
	if value, ok := _u.mutation.IdToken(); ok {
		_spec.SetField(account.FieldIdToken, field.TypeString, value)
	}
	if _u.mutation.IdTokenCleared() {
		_spec.ClearField(account.FieldIdToken, field.TypeString)
	}
	if value, ok := _u.mutation.SessionState(); ok {
		_spec.SetField(account.FieldSessionState, field.TypeString, value)
	}
	if _u.mutation.SessionStateCleared() {
		_spec.ClearField(account.FieldSessionState, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(account.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetUserId sets the "userId" field.
func (_u *AccountUpdateOne) SetUserId(v string) *AccountUpdateOne {
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableUserId(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AccountUpdateOne) SetProvider(v string) *AccountUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableProvider(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderAccountId sets the "providerAccountId" field.
func (_u *AccountUpdateOne) SetProviderAccountId(v string) *AccountUpdateOne {
	_u.mutation.SetProviderAccountId(v)
	return _u
}

// SetNillableProviderAccountId sets the "providerAccountId" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableProviderAccountId(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetProviderAccountId(*v)
	}
	return _u
}

// SetAccessToken sets the "accessToken" field.
func (_u *AccountUpdateOne) SetAccessToken(v string) *AccountUpdateOne {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "accessToken" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableAccessToken(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// ClearAccessToken clears the value of the "accessToken" field.
func (_u *AccountUpdateOne) ClearAccessToken() *AccountUpdateOne {
	_u.mutation.ClearAccessToken()
	return _u
}

// SetRefreshToken sets the "refreshToken" field.
func (_u *AccountUpdateOne) SetRefreshToken(v string) *AccountUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refreshToken" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableRefreshToken(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refreshToken" field.
func (_u *AccountUpdateOne) ClearRefreshToken() *AccountUpdateOne {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetExpiresAt sets the "expiresAt" field.
func (_u *AccountUpdateOne) SetExpiresAt(v int) *AccountUpdateOne {
	_u.mutation.ResetExpiresAt()
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expiresAt" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableExpiresAt(v *int) *AccountUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// AddExpiresAt adds value to the "expiresAt" field.
func (_u *AccountUpdateOne) AddExpiresAt(v int) *AccountUpdateOne {
	_u.mutation.AddExpiresAt(v)
	return _u
}

// ClearExpiresAt clears the value of the "expiresAt" field.
func (_u *AccountUpdateOne) ClearExpiresAt() *AccountUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetTokenType sets the "tokenType" field.
func (_u *AccountUpdateOne) SetTokenType(v string) *AccountUpdateOne {
	_u.mutation.SetTokenType(v)
	return _u
}

// SetNillableTokenType sets the "tokenType" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableTokenType(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetTokenType(*v)
	}
	return _u
}

// ClearTokenType clears the value of the "tokenType" field.
func (_u *AccountUpdateOne) ClearTokenType() *AccountUpdateOne {
	_u.mutation.ClearTokenType()
	return _u
}

// SetScope sets the "scope" field.
func (_u *AccountUpdateOne) SetScope(v string) *AccountUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableScope(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// ClearScope clears the value of the "scope" field.
func (_u *AccountUpdateOne) ClearScope() *AccountUpdateOne {
	_u.mutation.ClearScope()
	return _u
}

// SetIdToken sets the "idToken" field.
func (_u *AccountUpdateOne) SetIdToken(v string) *AccountUpdateOne {
	_u.mutation.SetIdToken(v)
	return _u
}

// SetNillableIdToken sets the "idToken" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableIdToken(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetIdToken(*v)
	}
	return _u
}

// ClearIdToken clears the value of the "idToken" field.
func (_u *AccountUpdateOne) ClearIdToken() *AccountUpdateOne {
	_u.mutation.ClearIdToken()
	return _u
}

// SetSessionState sets the "sessionState" field.
func (_u *AccountUpdateOne) SetSessionState(v string) *AccountUpdateOne {
	_u.mutation.SetSessionState(v)
	return _u
}

// SetNillableSessionState sets the "sessionState" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableSessionState(v *string) *AccountUpdateOne {
	if v != nil {
		_u.SetSessionState(*v)
	}
	return _u
}

// ClearSessionState clears the value of the "sessionState" field.
func (_u *AccountUpdateOne) ClearSessionState() *AccountUpdateOne {
	_u.mutation.ClearSessionState()
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *AccountUpdateOne) SetCreatedAt(v time.Time) *AccountUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *AccountUpdateOne) SetNillableCreatedAt(v *time.Time) *AccountUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *AccountUpdateOne) SetUpdatedAt(v time.Time) *AccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *AccountUpdateOne) SetUserID(id string) *AccountUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AccountUpdateOne) SetUser(v *User) *AccountUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the AccountMutation object of the builder.
func (_u *AccountUpdateOne) Mutation() *AccountMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AccountUpdateOne) ClearUser() *AccountUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the AccountUpdate builder.
func (_u *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Account entity.
func (_u *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := account.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Account.user"`)
	}
	return nil
}

func (_u *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(account.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderAccountId(); ok {
		_spec.SetField(account.FieldProviderAccountId, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(account.FieldAccessToken, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCleared() {
		_spec.ClearField(account.FieldAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(account.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(account.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(account.FieldExpiresAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExpiresAt(); ok {
		_spec.AddField(account.FieldExpiresAt, field.TypeInt, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(account.FieldExpiresAt, field.TypeInt)
	}
	if value, ok := _u.mutation.TokenType(); ok {
		_spec.SetField(account.FieldTokenType, field.TypeString, value)
	}
	if _u.mutation.TokenTypeCleared() {
		_spec.ClearField(account.FieldTokenType, field.TypeString)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(account.FieldScope, field.TypeString, value)
	}
	if _u.mutation.ScopeCleared() {
		_spec.ClearField(account.FieldScope, field.TypeString)
	}
	if value, ok := _u.mutation.IdToken(); ok {
		_spec.SetField(account.FieldIdToken, field.TypeString, value)
	}
	if _u.mutation.IdTokenCleared() {
		_spec.ClearField(account.FieldIdToken, field.TypeString)
	}
	if value, ok := _u.mutation.SessionState(); ok {
		_spec.SetField(account.FieldSessionState, field.TypeString, value)
	}
	if _u.mutation.SessionStateCleared() {
		_spec.ClearField(account.FieldSessionState, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(account.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.UserTable,
			Columns: []string{account.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Account{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
