// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shuTwT/nex-api/ent/advertisement"
)

// Advertisement is the model entity for the Advertisement schema.
type Advertisement struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Image holds the value of the "image" field.
	Image string `json:"image,omitempty"`
	// ImageWidth holds the value of the "imageWidth" field.
	ImageWidth int `json:"imageWidth,omitempty"`
	// ImageHeight holds the value of the "imageHeight" field.
	ImageHeight int `json:"imageHeight,omitempty"`
	// Link holds the value of the "link" field.
	Link string `json:"link,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Position holds the value of the "position" field.
	Position string `json:"position,omitempty"`
	// IsActive holds the value of the "isActive" field.
	IsActive bool `json:"isActive,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt    time.Time `json:"updatedAt,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Advertisement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case advertisement.FieldIsActive:
			values[i] = new(sql.NullBool)
		case advertisement.FieldImageWidth, advertisement.FieldImageHeight:
			values[i] = new(sql.NullInt64)
		case advertisement.FieldID, advertisement.FieldImage, advertisement.FieldLink, advertisement.FieldTitle, advertisement.FieldPosition:
			values[i] = new(sql.NullString)
		case advertisement.FieldCreatedAt, advertisement.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Advertisement fields.
func (_m *Advertisement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case advertisement.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case advertisement.FieldImage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image", values[i])
			} else if value.Valid {
				_m.Image = value.String
			}
		case advertisement.FieldImageWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field imageWidth", values[i])
			} else if value.Valid {
				_m.ImageWidth = int(value.Int64)
			}
		case advertisement.FieldImageHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field imageHeight", values[i])
			} else if value.Valid {
				_m.ImageHeight = int(value.Int64)
			}
		case advertisement.FieldLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field link", values[i])
			} else if value.Valid {
				_m.Link = value.String
			}
		case advertisement.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case advertisement.FieldPosition:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = value.String
			}
		case advertisement.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field isActive", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case advertisement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case advertisement.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Advertisement.
// This includes values selected through modifiers, order, etc.
func (_m *Advertisement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Advertisement.
// Note that you need to call Advertisement.Unwrap() before calling this method if this Advertisement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Advertisement) Update() *AdvertisementUpdateOne {
	return NewAdvertisementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Advertisement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Advertisement) Unwrap() *Advertisement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Advertisement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Advertisement) String() string {
	var builder strings.Builder
	builder.WriteString("Advertisement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("image=")
	builder.WriteString(_m.Image)
	builder.WriteString(", ")
	builder.WriteString("imageWidth=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImageWidth))
	builder.WriteString(", ")
	builder.WriteString("imageHeight=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImageHeight))
	builder.WriteString(", ")
	builder.WriteString("link=")
	builder.WriteString(_m.Link)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(_m.Position)
	builder.WriteString(", ")
	builder.WriteString("isActive=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Advertisements is a parsable slice of Advertisement.
type Advertisements []*Advertisement
