// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shuTwT/nex-api/ent/api"
	"github.com/shuTwT/nex-api/ent/apiparameter"
)

// ApiParameter is the model entity for the ApiParameter schema.
type ApiParameter struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ApiId holds the value of the "apiId" field.
	ApiId string `json:"apiId,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Required holds the value of the "required" field.
	Required bool `json:"required,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// DefaultValue holds the value of the "defaultValue" field.
	DefaultValue string `json:"defaultValue,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ApiParameterQuery when eager-loading is set.
	Edges        ApiParameterEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ApiParameterEdges holds the relations/edges for other nodes in the graph.
type ApiParameterEdges struct {
	// API holds the value of the api edge.
	API *Api `json:"api,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// APIOrErr returns the API value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ApiParameterEdges) APIOrErr() (*Api, error) {
	if e.API != nil {
		return e.API, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: api.Label}
	}
	return nil, &NotLoadedError{edge: "api"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ApiParameter) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apiparameter.FieldRequired:
			values[i] = new(sql.NullBool)
		case apiparameter.FieldID, apiparameter.FieldApiId, apiparameter.FieldName, apiparameter.FieldType, apiparameter.FieldDescription, apiparameter.FieldDefaultValue:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ApiParameter fields.
func (_m *ApiParameter) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apiparameter.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case apiparameter.FieldApiId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field apiId", values[i])
			} else if value.Valid {
				_m.ApiId = value.String
			}
		case apiparameter.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case apiparameter.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case apiparameter.FieldRequired:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field required", values[i])
			} else if value.Valid {
				_m.Required = value.Bool
			}
		case apiparameter.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case apiparameter.FieldDefaultValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field defaultValue", values[i])
			} else if value.Valid {
				_m.DefaultValue = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ApiParameter.
// This includes values selected through modifiers, order, etc.
func (_m *ApiParameter) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAPI queries the "api" edge of the ApiParameter entity.
func (_m *ApiParameter) QueryAPI() *APIQuery {
	return NewApiParameterClient(_m.config).QueryAPI(_m)
}

// Update returns a builder for updating this ApiParameter.
// Note that you need to call ApiParameter.Unwrap() before calling this method if this ApiParameter
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ApiParameter) Update() *ApiParameterUpdateOne {
	return NewApiParameterClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ApiParameter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ApiParameter) Unwrap() *ApiParameter {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ApiParameter is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ApiParameter) String() string {
	var builder strings.Builder
	builder.WriteString("ApiParameter(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("apiId=")
	builder.WriteString(_m.ApiId)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("required=")
	builder.WriteString(fmt.Sprintf("%v", _m.Required))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("defaultValue=")
	builder.WriteString(_m.DefaultValue)
	builder.WriteByte(')')
	return builder.String()
}

// ApiParameters is a parsable slice of ApiParameter.
type ApiParameters []*ApiParameter
