// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/nex-api/ent/api"
	"github.com/shuTwT/nex-api/ent/apiusage"
	"github.com/shuTwT/nex-api/ent/predicate"
	"github.com/shuTwT/nex-api/ent/user"
)

// ApiUsageUpdate is the builder for updating ApiUsage entities.
type ApiUsageUpdate struct {
	config
	hooks    []Hook
	mutation *ApiUsageMutation
}

// Where appends a list predicates to the ApiUsageUpdate builder.
func (_u *ApiUsageUpdate) Where(ps ...predicate.ApiUsage) *ApiUsageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserId sets the "userId" field.
func (_u *ApiUsageUpdate) SetUserId(v string) *ApiUsageUpdate {
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (_u *ApiUsageUpdate) SetNillableUserId(v *string) *ApiUsageUpdate {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// SetApiId sets the "apiId" field.
func (_u *ApiUsageUpdate) SetApiId(v string) *ApiUsageUpdate {
	_u.mutation.SetApiId(v)
	return _u
}

// SetNillableApiId sets the "apiId" field if the given value is not nil.
func (_u *ApiUsageUpdate) SetNillableApiId(v *string) *ApiUsageUpdate {
	if v != nil {
		_u.SetApiId(*v)
	}
	return _u
}

// SetCredits sets the "credits" field.
func (_u *ApiUsageUpdate) SetCredits(v int) *ApiUsageUpdate {
	_u.mutation.ResetCredits()
	_u.mutation.SetCredits(v)
	return _u
}

// SetNillableCredits sets the "credits" field if the given value is not nil.
func (_u *ApiUsageUpdate) SetNillableCredits(v *int) *ApiUsageUpdate {
	if v != nil {
		_u.SetCredits(*v)
	}
	return _u
}

// AddCredits adds value to the "credits" field.
func (_u *ApiUsageUpdate) AddCredits(v int) *ApiUsageUpdate {
	_u.mutation.AddCredits(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ApiUsageUpdate) SetStatus(v string) *ApiUsageUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ApiUsageUpdate) SetNillableStatus(v *string) *ApiUsageUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *ApiUsageUpdate) SetCreatedAt(v time.Time) *ApiUsageUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *ApiUsageUpdate) SetNillableCreatedAt(v *time.Time) *ApiUsageUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ApiUsageUpdate) SetUserID(id string) *ApiUsageUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ApiUsageUpdate) SetUser(v *User) *ApiUsageUpdate {
	return _u.SetUserID(v.ID)
}

// SetAPIID sets the "api" edge to the Api entity by ID.
func (_u *ApiUsageUpdate) SetAPIID(id string) *ApiUsageUpdate {
	_u.mutation.SetAPIID(id)
	return _u
}

// SetAPI sets the "api" edge to the Api entity.
func (_u *ApiUsageUpdate) SetAPI(v *Api) *ApiUsageUpdate {
	return _u.SetAPIID(v.ID)
}

// Mutation returns the ApiUsageMutation object of the builder.
func (_u *ApiUsageUpdate) Mutation() *ApiUsageMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ApiUsageUpdate) ClearUser() *ApiUsageUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPI clears the "api" edge to the Api entity.
func (_u *ApiUsageUpdate) ClearAPI() *ApiUsageUpdate {
	_u.mutation.ClearAPI()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApiUsageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiUsageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApiUsageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiUsageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiUsageUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiUsage.user"`)
	}
	if _u.mutation.APICleared() && len(_u.mutation.APIIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiUsage.api"`)
	}
	return nil
}

func (_u *ApiUsageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apiusage.Table, apiusage.Columns, sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Credits(); ok {
		_spec.SetField(apiusage.FieldCredits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCredits(); ok {
		_spec.AddField(apiusage.FieldCredits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(apiusage.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(apiusage.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apiusage.UserTable,
			Columns: []string{apiusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apiusage.UserTable,
			Columns: []string{apiusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APICleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apiusage.APITable,
			Columns: []string{apiusage.APIColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(api.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apiusage.APITable,
			Columns: []string{apiusage.APIColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(api.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apiusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApiUsageUpdateOne is the builder for updating a single ApiUsage entity.
type ApiUsageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApiUsageMutation
}

// SetUserId sets the "userId" field.
func (_u *ApiUsageUpdateOne) SetUserId(v string) *ApiUsageUpdateOne {
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (_u *ApiUsageUpdateOne) SetNillableUserId(v *string) *ApiUsageUpdateOne {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// SetApiId sets the "apiId" field.
func (_u *ApiUsageUpdateOne) SetApiId(v string) *ApiUsageUpdateOne {
	_u.mutation.SetApiId(v)
	return _u
}

// SetNillableApiId sets the "apiId" field if the given value is not nil.
func (_u *ApiUsageUpdateOne) SetNillableApiId(v *string) *ApiUsageUpdateOne {
	if v != nil {
		_u.SetApiId(*v)
	}
	return _u
}

// SetCredits sets the "credits" field.
func (_u *ApiUsageUpdateOne) SetCredits(v int) *ApiUsageUpdateOne {
	_u.mutation.ResetCredits()
	_u.mutation.SetCredits(v)
	return _u
}

// SetNillableCredits sets the "credits" field if the given value is not nil.
func (_u *ApiUsageUpdateOne) SetNillableCredits(v *int) *ApiUsageUpdateOne {
	if v != nil {
		_u.SetCredits(*v)
	}
	return _u
}

// AddCredits adds value to the "credits" field.
func (_u *ApiUsageUpdateOne) AddCredits(v int) *ApiUsageUpdateOne {
	_u.mutation.AddCredits(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ApiUsageUpdateOne) SetStatus(v string) *ApiUsageUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ApiUsageUpdateOne) SetNillableStatus(v *string) *ApiUsageUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *ApiUsageUpdateOne) SetCreatedAt(v time.Time) *ApiUsageUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *ApiUsageUpdateOne) SetNillableCreatedAt(v *time.Time) *ApiUsageUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *ApiUsageUpdateOne) SetUserID(id string) *ApiUsageUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ApiUsageUpdateOne) SetUser(v *User) *ApiUsageUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAPIID sets the "api" edge to the Api entity by ID.
func (_u *ApiUsageUpdateOne) SetAPIID(id string) *ApiUsageUpdateOne {
	_u.mutation.SetAPIID(id)
	return _u
}

// SetAPI sets the "api" edge to the Api entity.
func (_u *ApiUsageUpdateOne) SetAPI(v *Api) *ApiUsageUpdateOne {
	return _u.SetAPIID(v.ID)
}

// Mutation returns the ApiUsageMutation object of the builder.
func (_u *ApiUsageUpdateOne) Mutation() *ApiUsageMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ApiUsageUpdateOne) ClearUser() *ApiUsageUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPI clears the "api" edge to the Api entity.
func (_u *ApiUsageUpdateOne) ClearAPI() *ApiUsageUpdateOne {
	_u.mutation.ClearAPI()
	return _u
}

// Where appends a list predicates to the ApiUsageUpdate builder.
func (_u *ApiUsageUpdateOne) Where(ps ...predicate.ApiUsage) *ApiUsageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApiUsageUpdateOne) Select(field string, fields ...string) *ApiUsageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ApiUsage entity.
func (_u *ApiUsageUpdateOne) Save(ctx context.Context) (*ApiUsage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiUsageUpdateOne) SaveX(ctx context.Context) *ApiUsage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApiUsageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiUsageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiUsageUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiUsage.user"`)
	}
	if _u.mutation.APICleared() && len(_u.mutation.APIIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiUsage.api"`)
	}
	return nil
}

func (_u *ApiUsageUpdateOne) sqlSave(ctx context.Context) (_node *ApiUsage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apiusage.Table, apiusage.Columns, sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApiUsage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apiusage.FieldID)
		for _, f := range fields {
			if !apiusage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apiusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Credits(); ok {
		_spec.SetField(apiusage.FieldCredits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCredits(); ok {
		_spec.AddField(apiusage.FieldCredits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(apiusage.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(apiusage.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apiusage.UserTable,
			Columns: []string{apiusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apiusage.UserTable,
			Columns: []string{apiusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APICleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apiusage.APITable,
			Columns: []string{apiusage.APIColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(api.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apiusage.APITable,
			Columns: []string{apiusage.APIColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(api.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ApiUsage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apiusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
