// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/nex-api/ent/mcpservice"
	"github.com/shuTwT/nex-api/ent/mcpusage"
	"github.com/shuTwT/nex-api/ent/predicate"
)

// McpServiceUpdate is the builder for updating McpService entities.
type McpServiceUpdate struct {
	config
	hooks    []Hook
	mutation *McpServiceMutation
}

// Where appends a list predicates to the McpServiceUpdate builder.
func (_u *McpServiceUpdate) Where(ps ...predicate.McpService) *McpServiceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *McpServiceUpdate) SetName(v string) *McpServiceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *McpServiceUpdate) SetNillableName(v *string) *McpServiceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIdentifier sets the "identifier" field.
func (_u *McpServiceUpdate) SetIdentifier(v string) *McpServiceUpdate {
	_u.mutation.SetIdentifier(v)
	return _u
}

// SetNillableIdentifier sets the "identifier" field if the given value is not nil.
func (_u *McpServiceUpdate) SetNillableIdentifier(v *string) *McpServiceUpdate {
	if v != nil {
		_u.SetIdentifier(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *McpServiceUpdate) SetType(v string) *McpServiceUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *McpServiceUpdate) SetNillableType(v *string) *McpServiceUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetCommand sets the "command" field.
func (_u *McpServiceUpdate) SetCommand(v string) *McpServiceUpdate {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *McpServiceUpdate) SetNillableCommand(v *string) *McpServiceUpdate {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// ClearCommand clears the value of the "command" field.
func (_u *McpServiceUpdate) ClearCommand() *McpServiceUpdate {
	_u.mutation.ClearCommand()
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *McpServiceUpdate) SetEndpoint(v string) *McpServiceUpdate {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *McpServiceUpdate) SetNillableEndpoint(v *string) *McpServiceUpdate {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// ClearEndpoint clears the value of the "endpoint" field.
func (_u *McpServiceUpdate) ClearEndpoint() *McpServiceUpdate {
	_u.mutation.ClearEndpoint()
	return _u
}

// SetEnvVars sets the "envVars" field.
func (_u *McpServiceUpdate) SetEnvVars(v string) *McpServiceUpdate {
	_u.mutation.SetEnvVars(v)
	return _u
}

// SetNillableEnvVars sets the "envVars" field if the given value is not nil.
func (_u *McpServiceUpdate) SetNillableEnvVars(v *string) *McpServiceUpdate {
	if v != nil {
		_u.SetEnvVars(*v)
	}
	return _u
}

// ClearEnvVars clears the value of the "envVars" field.
func (_u *McpServiceUpdate) ClearEnvVars() *McpServiceUpdate {
	_u.mutation.ClearEnvVars()
	return _u
}

// SetPricing sets the "pricing" field.
func (_u *McpServiceUpdate) SetPricing(v int) *McpServiceUpdate {
	_u.mutation.ResetPricing()
	_u.mutation.SetPricing(v)
	return _u
}

// SetNillablePricing sets the "pricing" field if the given value is not nil.
func (_u *McpServiceUpdate) SetNillablePricing(v *int) *McpServiceUpdate {
	if v != nil {
		_u.SetPricing(*v)
	}
	return _u
}

// AddPricing adds value to the "pricing" field.
func (_u *McpServiceUpdate) AddPricing(v int) *McpServiceUpdate {
	_u.mutation.AddPricing(v)
	return _u
}

// SetIsActive sets the "isActive" field.
func (_u *McpServiceUpdate) SetIsActive(v bool) *McpServiceUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "isActive" field if the given value is not nil.
func (_u *McpServiceUpdate) SetNillableIsActive(v *bool) *McpServiceUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCallCount sets the "callCount" field.
func (_u *McpServiceUpdate) SetCallCount(v int) *McpServiceUpdate {
	_u.mutation.ResetCallCount()
	_u.mutation.SetCallCount(v)
	return _u
}

// SetNillableCallCount sets the "callCount" field if the given value is not nil.
func (_u *McpServiceUpdate) SetNillableCallCount(v *int) *McpServiceUpdate {
	if v != nil {
		_u.SetCallCount(*v)
	}
	return _u
}

// AddCallCount adds value to the "callCount" field.
func (_u *McpServiceUpdate) AddCallCount(v int) *McpServiceUpdate {
	_u.mutation.AddCallCount(v)
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *McpServiceUpdate) SetCreatedAt(v time.Time) *McpServiceUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *McpServiceUpdate) SetNillableCreatedAt(v *time.Time) *McpServiceUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *McpServiceUpdate) SetUpdatedAt(v time.Time) *McpServiceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUsageRecordIDs adds the "usageRecords" edge to the McpUsage entity by IDs.
func (_u *McpServiceUpdate) AddUsageRecordIDs(ids ...string) *McpServiceUpdate {
	_u.mutation.AddUsageRecordIDs(ids...)
	return _u
}

// AddUsageRecords adds the "usageRecords" edges to the McpUsage entity.
func (_u *McpServiceUpdate) AddUsageRecords(v ...*McpUsage) *McpServiceUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageRecordIDs(ids...)
}

// Mutation returns the McpServiceMutation object of the builder.
func (_u *McpServiceUpdate) Mutation() *McpServiceMutation {
	return _u.mutation
}

// ClearUsageRecords clears all "usageRecords" edges to the McpUsage entity.
func (_u *McpServiceUpdate) ClearUsageRecords() *McpServiceUpdate {
	_u.mutation.ClearUsageRecords()
	return _u
}

// RemoveUsageRecordIDs removes the "usageRecords" edge to McpUsage entities by IDs.
func (_u *McpServiceUpdate) RemoveUsageRecordIDs(ids ...string) *McpServiceUpdate {
	_u.mutation.RemoveUsageRecordIDs(ids...)
	return _u
}

// RemoveUsageRecords removes "usageRecords" edges to McpUsage entities.
func (_u *McpServiceUpdate) RemoveUsageRecords(v ...*McpUsage) *McpServiceUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageRecordIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *McpServiceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *McpServiceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *McpServiceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *McpServiceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *McpServiceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mcpservice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *McpServiceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(mcpservice.Table, mcpservice.Columns, sqlgraph.NewFieldSpec(mcpservice.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mcpservice.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Identifier(); ok {
		_spec.SetField(mcpservice.FieldIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(mcpservice.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(mcpservice.FieldCommand, field.TypeString, value)
	}
	if _u.mutation.CommandCleared() {
		_spec.ClearField(mcpservice.FieldCommand, field.TypeString)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(mcpservice.FieldEndpoint, field.TypeString, value)
	}
	if _u.mutation.EndpointCleared() {
		_spec.ClearField(mcpservice.FieldEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.EnvVars(); ok {
		_spec.SetField(mcpservice.FieldEnvVars, field.TypeString, value)
	}
	if _u.mutation.EnvVarsCleared() {
		_spec.ClearField(mcpservice.FieldEnvVars, field.TypeString)
	}
	if value, ok := _u.mutation.Pricing(); ok {
		_spec.SetField(mcpservice.FieldPricing, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPricing(); ok {
		_spec.AddField(mcpservice.FieldPricing, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(mcpservice.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CallCount(); ok {
		_spec.SetField(mcpservice.FieldCallCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCallCount(); ok {
		_spec.AddField(mcpservice.FieldCallCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(mcpservice.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mcpservice.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsageRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpservice.UsageRecordsTable,
			Columns: []string{mcpservice.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpusage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageRecordsIDs(); len(nodes) > 0 && !_u.mutation.UsageRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpservice.UsageRecordsTable,
			Columns: []string{mcpservice.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpusage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpservice.UsageRecordsTable,
			Columns: []string{mcpservice.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpusage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mcpservice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// McpServiceUpdateOne is the builder for updating a single McpService entity.
type McpServiceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *McpServiceMutation
}

// SetName sets the "name" field.
func (_u *McpServiceUpdateOne) SetName(v string) *McpServiceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *McpServiceUpdateOne) SetNillableName(v *string) *McpServiceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIdentifier sets the "identifier" field.
func (_u *McpServiceUpdateOne) SetIdentifier(v string) *McpServiceUpdateOne {
	_u.mutation.SetIdentifier(v)
	return _u
}

// SetNillableIdentifier sets the "identifier" field if the given value is not nil.
func (_u *McpServiceUpdateOne) SetNillableIdentifier(v *string) *McpServiceUpdateOne {
	if v != nil {
		_u.SetIdentifier(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *McpServiceUpdateOne) SetType(v string) *McpServiceUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *McpServiceUpdateOne) SetNillableType(v *string) *McpServiceUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetCommand sets the "command" field.
func (_u *McpServiceUpdateOne) SetCommand(v string) *McpServiceUpdateOne {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *McpServiceUpdateOne) SetNillableCommand(v *string) *McpServiceUpdateOne {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// ClearCommand clears the value of the "command" field.
func (_u *McpServiceUpdateOne) ClearCommand() *McpServiceUpdateOne {
	_u.mutation.ClearCommand()
	return _u
}

// SetEndpoint sets the "endpoint" field.
func (_u *McpServiceUpdateOne) SetEndpoint(v string) *McpServiceUpdateOne {
	_u.mutation.SetEndpoint(v)
	return _u
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (_u *McpServiceUpdateOne) SetNillableEndpoint(v *string) *McpServiceUpdateOne {
	if v != nil {
		_u.SetEndpoint(*v)
	}
	return _u
}

// ClearEndpoint clears the value of the "endpoint" field.
func (_u *McpServiceUpdateOne) ClearEndpoint() *McpServiceUpdateOne {
	_u.mutation.ClearEndpoint()
	return _u
}

// SetEnvVars sets the "envVars" field.
func (_u *McpServiceUpdateOne) SetEnvVars(v string) *McpServiceUpdateOne {
	_u.mutation.SetEnvVars(v)
	return _u
}

// SetNillableEnvVars sets the "envVars" field if the given value is not nil.
func (_u *McpServiceUpdateOne) SetNillableEnvVars(v *string) *McpServiceUpdateOne {
	if v != nil {
		_u.SetEnvVars(*v)
	}
	return _u
}

// ClearEnvVars clears the value of the "envVars" field.
func (_u *McpServiceUpdateOne) ClearEnvVars() *McpServiceUpdateOne {
	_u.mutation.ClearEnvVars()
	return _u
}

// SetPricing sets the "pricing" field.
func (_u *McpServiceUpdateOne) SetPricing(v int) *McpServiceUpdateOne {
	_u.mutation.ResetPricing()
	_u.mutation.SetPricing(v)
	return _u
}

// SetNillablePricing sets the "pricing" field if the given value is not nil.
func (_u *McpServiceUpdateOne) SetNillablePricing(v *int) *McpServiceUpdateOne {
	if v != nil {
		_u.SetPricing(*v)
	}
	return _u
}

// AddPricing adds value to the "pricing" field.
func (_u *McpServiceUpdateOne) AddPricing(v int) *McpServiceUpdateOne {
	_u.mutation.AddPricing(v)
	return _u
}

// SetIsActive sets the "isActive" field.
func (_u *McpServiceUpdateOne) SetIsActive(v bool) *McpServiceUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "isActive" field if the given value is not nil.
func (_u *McpServiceUpdateOne) SetNillableIsActive(v *bool) *McpServiceUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCallCount sets the "callCount" field.
func (_u *McpServiceUpdateOne) SetCallCount(v int) *McpServiceUpdateOne {
	_u.mutation.ResetCallCount()
	_u.mutation.SetCallCount(v)
	return _u
}

// SetNillableCallCount sets the "callCount" field if the given value is not nil.
func (_u *McpServiceUpdateOne) SetNillableCallCount(v *int) *McpServiceUpdateOne {
	if v != nil {
		_u.SetCallCount(*v)
	}
	return _u
}

// AddCallCount adds value to the "callCount" field.
func (_u *McpServiceUpdateOne) AddCallCount(v int) *McpServiceUpdateOne {
	_u.mutation.AddCallCount(v)
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *McpServiceUpdateOne) SetCreatedAt(v time.Time) *McpServiceUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *McpServiceUpdateOne) SetNillableCreatedAt(v *time.Time) *McpServiceUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *McpServiceUpdateOne) SetUpdatedAt(v time.Time) *McpServiceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUsageRecordIDs adds the "usageRecords" edge to the McpUsage entity by IDs.
func (_u *McpServiceUpdateOne) AddUsageRecordIDs(ids ...string) *McpServiceUpdateOne {
	_u.mutation.AddUsageRecordIDs(ids...)
	return _u
}

// AddUsageRecords adds the "usageRecords" edges to the McpUsage entity.
func (_u *McpServiceUpdateOne) AddUsageRecords(v ...*McpUsage) *McpServiceUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageRecordIDs(ids...)
}

// Mutation returns the McpServiceMutation object of the builder.
func (_u *McpServiceUpdateOne) Mutation() *McpServiceMutation {
	return _u.mutation
}

// ClearUsageRecords clears all "usageRecords" edges to the McpUsage entity.
func (_u *McpServiceUpdateOne) ClearUsageRecords() *McpServiceUpdateOne {
	_u.mutation.ClearUsageRecords()
	return _u
}

// RemoveUsageRecordIDs removes the "usageRecords" edge to McpUsage entities by IDs.
func (_u *McpServiceUpdateOne) RemoveUsageRecordIDs(ids ...string) *McpServiceUpdateOne {
	_u.mutation.RemoveUsageRecordIDs(ids...)
	return _u
}

// RemoveUsageRecords removes "usageRecords" edges to McpUsage entities.
func (_u *McpServiceUpdateOne) RemoveUsageRecords(v ...*McpUsage) *McpServiceUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageRecordIDs(ids...)
}

// Where appends a list predicates to the McpServiceUpdate builder.
func (_u *McpServiceUpdateOne) Where(ps ...predicate.McpService) *McpServiceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *McpServiceUpdateOne) Select(field string, fields ...string) *McpServiceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated McpService entity.
func (_u *McpServiceUpdateOne) Save(ctx context.Context) (*McpService, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *McpServiceUpdateOne) SaveX(ctx context.Context) *McpService {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *McpServiceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *McpServiceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *McpServiceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mcpservice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *McpServiceUpdateOne) sqlSave(ctx context.Context) (_node *McpService, err error) {
	_spec := sqlgraph.NewUpdateSpec(mcpservice.Table, mcpservice.Columns, sqlgraph.NewFieldSpec(mcpservice.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "McpService.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mcpservice.FieldID)
		for _, f := range fields {
			if !mcpservice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mcpservice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(mcpservice.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Identifier(); ok {
		_spec.SetField(mcpservice.FieldIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(mcpservice.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(mcpservice.FieldCommand, field.TypeString, value)
	}
	if _u.mutation.CommandCleared() {
		_spec.ClearField(mcpservice.FieldCommand, field.TypeString)
	}
	if value, ok := _u.mutation.Endpoint(); ok {
		_spec.SetField(mcpservice.FieldEndpoint, field.TypeString, value)
	}
	if _u.mutation.EndpointCleared() {
		_spec.ClearField(mcpservice.FieldEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.EnvVars(); ok {
		_spec.SetField(mcpservice.FieldEnvVars, field.TypeString, value)
	}
	if _u.mutation.EnvVarsCleared() {
		_spec.ClearField(mcpservice.FieldEnvVars, field.TypeString)
	}
	if value, ok := _u.mutation.Pricing(); ok {
		_spec.SetField(mcpservice.FieldPricing, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPricing(); ok {
		_spec.AddField(mcpservice.FieldPricing, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(mcpservice.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CallCount(); ok {
		_spec.SetField(mcpservice.FieldCallCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCallCount(); ok {
		_spec.AddField(mcpservice.FieldCallCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(mcpservice.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mcpservice.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsageRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpservice.UsageRecordsTable,
			Columns: []string{mcpservice.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpusage.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageRecordsIDs(); len(nodes) > 0 && !_u.mutation.UsageRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpservice.UsageRecordsTable,
			Columns: []string{mcpservice.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpusage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   mcpservice.UsageRecordsTable,
			Columns: []string{mcpservice.UsageRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpusage.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &McpService{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mcpservice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
