// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/nex-api/ent/mcpservice"
	"github.com/shuTwT/nex-api/ent/mcpusage"
	"github.com/shuTwT/nex-api/ent/predicate"
	"github.com/shuTwT/nex-api/ent/user"
)

// McpUsageUpdate is the builder for updating McpUsage entities.
type McpUsageUpdate struct {
	config
	hooks    []Hook
	mutation *McpUsageMutation
}

// Where appends a list predicates to the McpUsageUpdate builder.
func (_u *McpUsageUpdate) Where(ps ...predicate.McpUsage) *McpUsageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserId sets the "userId" field.
func (_u *McpUsageUpdate) SetUserId(v string) *McpUsageUpdate {
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (_u *McpUsageUpdate) SetNillableUserId(v *string) *McpUsageUpdate {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// SetMcpId sets the "mcpId" field.
func (_u *McpUsageUpdate) SetMcpId(v string) *McpUsageUpdate {
	_u.mutation.SetMcpId(v)
	return _u
}

// SetNillableMcpId sets the "mcpId" field if the given value is not nil.
func (_u *McpUsageUpdate) SetNillableMcpId(v *string) *McpUsageUpdate {
	if v != nil {
		_u.SetMcpId(*v)
	}
	return _u
}

// SetCredits sets the "credits" field.
func (_u *McpUsageUpdate) SetCredits(v int) *McpUsageUpdate {
	_u.mutation.ResetCredits()
	_u.mutation.SetCredits(v)
	return _u
}

// SetNillableCredits sets the "credits" field if the given value is not nil.
func (_u *McpUsageUpdate) SetNillableCredits(v *int) *McpUsageUpdate {
	if v != nil {
		_u.SetCredits(*v)
	}
	return _u
}

// AddCredits adds value to the "credits" field.
func (_u *McpUsageUpdate) AddCredits(v int) *McpUsageUpdate {
	_u.mutation.AddCredits(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *McpUsageUpdate) SetStatus(v string) *McpUsageUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *McpUsageUpdate) SetNillableStatus(v *string) *McpUsageUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *McpUsageUpdate) SetCreatedAt(v time.Time) *McpUsageUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *McpUsageUpdate) SetNillableCreatedAt(v *time.Time) *McpUsageUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *McpUsageUpdate) SetUserID(id string) *McpUsageUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *McpUsageUpdate) SetUser(v *User) *McpUsageUpdate {
	return _u.SetUserID(v.ID)
}

// SetMcpID sets the "mcp" edge to the McpService entity by ID.
func (_u *McpUsageUpdate) SetMcpID(id string) *McpUsageUpdate {
	_u.mutation.SetMcpID(id)
	return _u
}

// SetMcp sets the "mcp" edge to the McpService entity.
func (_u *McpUsageUpdate) SetMcp(v *McpService) *McpUsageUpdate {
	return _u.SetMcpID(v.ID)
}

// Mutation returns the McpUsageMutation object of the builder.
func (_u *McpUsageUpdate) Mutation() *McpUsageMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *McpUsageUpdate) ClearUser() *McpUsageUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearMcp clears the "mcp" edge to the McpService entity.
func (_u *McpUsageUpdate) ClearMcp() *McpUsageUpdate {
	_u.mutation.ClearMcp()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *McpUsageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *McpUsageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *McpUsageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *McpUsageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *McpUsageUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "McpUsage.user"`)
	}
	if _u.mutation.McpCleared() && len(_u.mutation.McpIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "McpUsage.mcp"`)
	}
	return nil
}

func (_u *McpUsageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mcpusage.Table, mcpusage.Columns, sqlgraph.NewFieldSpec(mcpusage.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Credits(); ok {
		_spec.SetField(mcpusage.FieldCredits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCredits(); ok {
		_spec.AddField(mcpusage.FieldCredits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mcpusage.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(mcpusage.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mcpusage.UserTable,
			Columns: []string{mcpusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mcpusage.UserTable,
			Columns: []string{mcpusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.McpCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mcpusage.McpTable,
			Columns: []string{mcpusage.McpColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpservice.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.McpIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mcpusage.McpTable,
			Columns: []string{mcpusage.McpColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpservice.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mcpusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// McpUsageUpdateOne is the builder for updating a single McpUsage entity.
type McpUsageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *McpUsageMutation
}

// SetUserId sets the "userId" field.
func (_u *McpUsageUpdateOne) SetUserId(v string) *McpUsageUpdateOne {
	_u.mutation.SetUserId(v)
	return _u
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (_u *McpUsageUpdateOne) SetNillableUserId(v *string) *McpUsageUpdateOne {
	if v != nil {
		_u.SetUserId(*v)
	}
	return _u
}

// SetMcpId sets the "mcpId" field.
func (_u *McpUsageUpdateOne) SetMcpId(v string) *McpUsageUpdateOne {
	_u.mutation.SetMcpId(v)
	return _u
}

// SetNillableMcpId sets the "mcpId" field if the given value is not nil.
func (_u *McpUsageUpdateOne) SetNillableMcpId(v *string) *McpUsageUpdateOne {
	if v != nil {
		_u.SetMcpId(*v)
	}
	return _u
}

// SetCredits sets the "credits" field.
func (_u *McpUsageUpdateOne) SetCredits(v int) *McpUsageUpdateOne {
	_u.mutation.ResetCredits()
	_u.mutation.SetCredits(v)
	return _u
}

// SetNillableCredits sets the "credits" field if the given value is not nil.
func (_u *McpUsageUpdateOne) SetNillableCredits(v *int) *McpUsageUpdateOne {
	if v != nil {
		_u.SetCredits(*v)
	}
	return _u
}

// AddCredits adds value to the "credits" field.
func (_u *McpUsageUpdateOne) AddCredits(v int) *McpUsageUpdateOne {
	_u.mutation.AddCredits(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *McpUsageUpdateOne) SetStatus(v string) *McpUsageUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *McpUsageUpdateOne) SetNillableStatus(v *string) *McpUsageUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *McpUsageUpdateOne) SetCreatedAt(v time.Time) *McpUsageUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *McpUsageUpdateOne) SetNillableCreatedAt(v *time.Time) *McpUsageUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *McpUsageUpdateOne) SetUserID(id string) *McpUsageUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *McpUsageUpdateOne) SetUser(v *User) *McpUsageUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetMcpID sets the "mcp" edge to the McpService entity by ID.
func (_u *McpUsageUpdateOne) SetMcpID(id string) *McpUsageUpdateOne {
	_u.mutation.SetMcpID(id)
	return _u
}

// SetMcp sets the "mcp" edge to the McpService entity.
func (_u *McpUsageUpdateOne) SetMcp(v *McpService) *McpUsageUpdateOne {
	return _u.SetMcpID(v.ID)
}

// Mutation returns the McpUsageMutation object of the builder.
func (_u *McpUsageUpdateOne) Mutation() *McpUsageMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *McpUsageUpdateOne) ClearUser() *McpUsageUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearMcp clears the "mcp" edge to the McpService entity.
func (_u *McpUsageUpdateOne) ClearMcp() *McpUsageUpdateOne {
	_u.mutation.ClearMcp()
	return _u
}

// Where appends a list predicates to the McpUsageUpdate builder.
func (_u *McpUsageUpdateOne) Where(ps ...predicate.McpUsage) *McpUsageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *McpUsageUpdateOne) Select(field string, fields ...string) *McpUsageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated McpUsage entity.
func (_u *McpUsageUpdateOne) Save(ctx context.Context) (*McpUsage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *McpUsageUpdateOne) SaveX(ctx context.Context) *McpUsage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *McpUsageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *McpUsageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *McpUsageUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "McpUsage.user"`)
	}
	if _u.mutation.McpCleared() && len(_u.mutation.McpIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "McpUsage.mcp"`)
	}
	return nil
}

func (_u *McpUsageUpdateOne) sqlSave(ctx context.Context) (_node *McpUsage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mcpusage.Table, mcpusage.Columns, sqlgraph.NewFieldSpec(mcpusage.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "McpUsage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mcpusage.FieldID)
		for _, f := range fields {
			if !mcpusage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mcpusage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Credits(); ok {
		_spec.SetField(mcpusage.FieldCredits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCredits(); ok {
		_spec.AddField(mcpusage.FieldCredits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mcpusage.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(mcpusage.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mcpusage.UserTable,
			Columns: []string{mcpusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mcpusage.UserTable,
			Columns: []string{mcpusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.McpCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mcpusage.McpTable,
			Columns: []string{mcpusage.McpColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpservice.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.McpIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   mcpusage.McpTable,
			Columns: []string{mcpusage.McpColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mcpservice.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &McpUsage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mcpusage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
