// Code generated by ent, DO NOT EDIT.

package apiparameter

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shuTwT/nex-api/backend/internal/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldContainsFold(FieldID, id))
}

// ApiId applies equality check predicate on the "apiId" field. It's identical to ApiIdEQ.
func ApiId(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEQ(FieldApiId, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEQ(FieldName, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEQ(FieldType, v))
}

// Required applies equality check predicate on the "required" field. It's identical to RequiredEQ.
func Required(v bool) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEQ(FieldRequired, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEQ(FieldDescription, v))
}

// DefaultValue applies equality check predicate on the "defaultValue" field. It's identical to DefaultValueEQ.
func DefaultValue(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEQ(FieldDefaultValue, v))
}

// ApiIdEQ applies the EQ predicate on the "apiId" field.
func ApiIdEQ(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEQ(FieldApiId, v))
}

// ApiIdNEQ applies the NEQ predicate on the "apiId" field.
func ApiIdNEQ(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldNEQ(FieldApiId, v))
}

// ApiIdIn applies the In predicate on the "apiId" field.
func ApiIdIn(vs ...string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldIn(FieldApiId, vs...))
}

// ApiIdNotIn applies the NotIn predicate on the "apiId" field.
func ApiIdNotIn(vs ...string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldNotIn(FieldApiId, vs...))
}

// ApiIdGT applies the GT predicate on the "apiId" field.
func ApiIdGT(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldGT(FieldApiId, v))
}

// ApiIdGTE applies the GTE predicate on the "apiId" field.
func ApiIdGTE(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldGTE(FieldApiId, v))
}

// ApiIdLT applies the LT predicate on the "apiId" field.
func ApiIdLT(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldLT(FieldApiId, v))
}

// ApiIdLTE applies the LTE predicate on the "apiId" field.
func ApiIdLTE(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldLTE(FieldApiId, v))
}

// ApiIdContains applies the Contains predicate on the "apiId" field.
func ApiIdContains(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldContains(FieldApiId, v))
}

// ApiIdHasPrefix applies the HasPrefix predicate on the "apiId" field.
func ApiIdHasPrefix(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldHasPrefix(FieldApiId, v))
}

// ApiIdHasSuffix applies the HasSuffix predicate on the "apiId" field.
func ApiIdHasSuffix(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldHasSuffix(FieldApiId, v))
}

// ApiIdEqualFold applies the EqualFold predicate on the "apiId" field.
func ApiIdEqualFold(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEqualFold(FieldApiId, v))
}

// ApiIdContainsFold applies the ContainsFold predicate on the "apiId" field.
func ApiIdContainsFold(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldContainsFold(FieldApiId, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldContainsFold(FieldType, v))
}

// RequiredEQ applies the EQ predicate on the "required" field.
func RequiredEQ(v bool) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEQ(FieldRequired, v))
}

// RequiredNEQ applies the NEQ predicate on the "required" field.
func RequiredNEQ(v bool) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldNEQ(FieldRequired, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldContainsFold(FieldDescription, v))
}

// DefaultValueEQ applies the EQ predicate on the "defaultValue" field.
func DefaultValueEQ(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEQ(FieldDefaultValue, v))
}

// DefaultValueNEQ applies the NEQ predicate on the "defaultValue" field.
func DefaultValueNEQ(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldNEQ(FieldDefaultValue, v))
}

// DefaultValueIn applies the In predicate on the "defaultValue" field.
func DefaultValueIn(vs ...string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldIn(FieldDefaultValue, vs...))
}

// DefaultValueNotIn applies the NotIn predicate on the "defaultValue" field.
func DefaultValueNotIn(vs ...string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldNotIn(FieldDefaultValue, vs...))
}

// DefaultValueGT applies the GT predicate on the "defaultValue" field.
func DefaultValueGT(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldGT(FieldDefaultValue, v))
}

// DefaultValueGTE applies the GTE predicate on the "defaultValue" field.
func DefaultValueGTE(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldGTE(FieldDefaultValue, v))
}

// DefaultValueLT applies the LT predicate on the "defaultValue" field.
func DefaultValueLT(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldLT(FieldDefaultValue, v))
}

// DefaultValueLTE applies the LTE predicate on the "defaultValue" field.
func DefaultValueLTE(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldLTE(FieldDefaultValue, v))
}

// DefaultValueContains applies the Contains predicate on the "defaultValue" field.
func DefaultValueContains(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldContains(FieldDefaultValue, v))
}

// DefaultValueHasPrefix applies the HasPrefix predicate on the "defaultValue" field.
func DefaultValueHasPrefix(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldHasPrefix(FieldDefaultValue, v))
}

// DefaultValueHasSuffix applies the HasSuffix predicate on the "defaultValue" field.
func DefaultValueHasSuffix(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldHasSuffix(FieldDefaultValue, v))
}

// DefaultValueIsNil applies the IsNil predicate on the "defaultValue" field.
func DefaultValueIsNil() predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldIsNull(FieldDefaultValue))
}

// DefaultValueNotNil applies the NotNil predicate on the "defaultValue" field.
func DefaultValueNotNil() predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldNotNull(FieldDefaultValue))
}

// DefaultValueEqualFold applies the EqualFold predicate on the "defaultValue" field.
func DefaultValueEqualFold(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldEqualFold(FieldDefaultValue, v))
}

// DefaultValueContainsFold applies the ContainsFold predicate on the "defaultValue" field.
func DefaultValueContainsFold(v string) predicate.ApiParameter {
	return predicate.ApiParameter(sql.FieldContainsFold(FieldDefaultValue, v))
}

// HasAPI applies the HasEdge predicate on the "api" edge.
func HasAPI() predicate.ApiParameter {
	return predicate.ApiParameter(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APITable, APIColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIWith applies the HasEdge predicate on the "api" edge with a given conditions (other predicates).
func HasAPIWith(preds ...predicate.Api) predicate.ApiParameter {
	return predicate.ApiParameter(func(s *sql.Selector) {
		step := newAPIStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ApiParameter) predicate.ApiParameter {
	return predicate.ApiParameter(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ApiParameter) predicate.ApiParameter {
	return predicate.ApiParameter(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ApiParameter) predicate.ApiParameter {
	return predicate.ApiParameter(sql.NotPredicates(p))
}
