// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/nex-api/backend/internal/database/ent/advertisement"
	"github.com/shuTwT/nex-api/backend/internal/database/ent/predicate"
)

// AdvertisementDelete is the builder for deleting a Advertisement entity.
type AdvertisementDelete struct {
	config
	hooks    []Hook
	mutation *AdvertisementMutation
}

// Where appends a list predicates to the AdvertisementDelete builder.
func (_d *AdvertisementDelete) Where(ps ...predicate.Advertisement) *AdvertisementDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AdvertisementDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdvertisementDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AdvertisementDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(advertisement.Table, sqlgraph.NewFieldSpec(advertisement.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AdvertisementDeleteOne is the builder for deleting a single Advertisement entity.
type AdvertisementDeleteOne struct {
	_d *AdvertisementDelete
}

// Where appends a list predicates to the AdvertisementDelete builder.
func (_d *AdvertisementDeleteOne) Where(ps ...predicate.Advertisement) *AdvertisementDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AdvertisementDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{advertisement.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdvertisementDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
