// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shuTwT/nex-api/backend/internal/database/ent/api"
	"github.com/shuTwT/nex-api/backend/internal/database/ent/apicategory"
)

// Api is the model entity for the Api schema.
type Api struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Alias holds the value of the "alias" field.
	Alias string `json:"alias,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// Method holds the value of the "method" field.
	Method string `json:"method,omitempty"`
	// CategoryId holds the value of the "categoryId" field.
	CategoryId string `json:"categoryId,omitempty"`
	// Pricing holds the value of the "pricing" field.
	Pricing int `json:"pricing,omitempty"`
	// Documentation holds the value of the "documentation" field.
	Documentation string `json:"documentation,omitempty"`
	// PreScript holds the value of the "preScript" field.
	PreScript string `json:"preScript,omitempty"`
	// PostScript holds the value of the "postScript" field.
	PostScript string `json:"postScript,omitempty"`
	// IsActive holds the value of the "isActive" field.
	IsActive bool `json:"isActive,omitempty"`
	// CallCount holds the value of the "callCount" field.
	CallCount int `json:"callCount,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ApiQuery when eager-loading is set.
	Edges        ApiEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ApiEdges holds the relations/edges for other nodes in the graph.
type ApiEdges struct {
	// Category holds the value of the category edge.
	Category *ApiCategory `json:"category,omitempty"`
	// Parameters holds the value of the parameters edge.
	Parameters []*ApiParameter `json:"parameters,omitempty"`
	// Responses holds the value of the responses edge.
	Responses []*ApiResponse `json:"responses,omitempty"`
	// UsageRecords holds the value of the usageRecords edge.
	UsageRecords []*ApiUsage `json:"usageRecords,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ApiEdges) CategoryOrErr() (*ApiCategory, error) {
	if e.Category != nil {
		return e.Category, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: apicategory.Label}
	}
	return nil, &NotLoadedError{edge: "category"}
}

// ParametersOrErr returns the Parameters value or an error if the edge
// was not loaded in eager-loading.
func (e ApiEdges) ParametersOrErr() ([]*ApiParameter, error) {
	if e.loadedTypes[1] {
		return e.Parameters, nil
	}
	return nil, &NotLoadedError{edge: "parameters"}
}

// ResponsesOrErr returns the Responses value or an error if the edge
// was not loaded in eager-loading.
func (e ApiEdges) ResponsesOrErr() ([]*ApiResponse, error) {
	if e.loadedTypes[2] {
		return e.Responses, nil
	}
	return nil, &NotLoadedError{edge: "responses"}
}

// UsageRecordsOrErr returns the UsageRecords value or an error if the edge
// was not loaded in eager-loading.
func (e ApiEdges) UsageRecordsOrErr() ([]*ApiUsage, error) {
	if e.loadedTypes[3] {
		return e.UsageRecords, nil
	}
	return nil, &NotLoadedError{edge: "usageRecords"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Api) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case api.FieldIsActive:
			values[i] = new(sql.NullBool)
		case api.FieldPricing, api.FieldCallCount:
			values[i] = new(sql.NullInt64)
		case api.FieldID, api.FieldName, api.FieldAlias, api.FieldDescription, api.FieldEndpoint, api.FieldMethod, api.FieldCategoryId, api.FieldDocumentation, api.FieldPreScript, api.FieldPostScript:
			values[i] = new(sql.NullString)
		case api.FieldCreatedAt, api.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Api fields.
func (_m *Api) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case api.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case api.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case api.FieldAlias:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alias", values[i])
			} else if value.Valid {
				_m.Alias = value.String
			}
		case api.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case api.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case api.FieldMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field method", values[i])
			} else if value.Valid {
				_m.Method = value.String
			}
		case api.FieldCategoryId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field categoryId", values[i])
			} else if value.Valid {
				_m.CategoryId = value.String
			}
		case api.FieldPricing:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pricing", values[i])
			} else if value.Valid {
				_m.Pricing = int(value.Int64)
			}
		case api.FieldDocumentation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field documentation", values[i])
			} else if value.Valid {
				_m.Documentation = value.String
			}
		case api.FieldPreScript:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field preScript", values[i])
			} else if value.Valid {
				_m.PreScript = value.String
			}
		case api.FieldPostScript:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field postScript", values[i])
			} else if value.Valid {
				_m.PostScript = value.String
			}
		case api.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field isActive", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case api.FieldCallCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field callCount", values[i])
			} else if value.Valid {
				_m.CallCount = int(value.Int64)
			}
		case api.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case api.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Api.
// This includes values selected through modifiers, order, etc.
func (_m *Api) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCategory queries the "category" edge of the Api entity.
func (_m *Api) QueryCategory() *ApiCategoryQuery {
	return NewAPIClient(_m.config).QueryCategory(_m)
}

// QueryParameters queries the "parameters" edge of the Api entity.
func (_m *Api) QueryParameters() *ApiParameterQuery {
	return NewAPIClient(_m.config).QueryParameters(_m)
}

// QueryResponses queries the "responses" edge of the Api entity.
func (_m *Api) QueryResponses() *ApiResponseQuery {
	return NewAPIClient(_m.config).QueryResponses(_m)
}

// QueryUsageRecords queries the "usageRecords" edge of the Api entity.
func (_m *Api) QueryUsageRecords() *ApiUsageQuery {
	return NewAPIClient(_m.config).QueryUsageRecords(_m)
}

// Update returns a builder for updating this Api.
// Note that you need to call Api.Unwrap() before calling this method if this Api
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Api) Update() *APIUpdateOne {
	return NewAPIClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Api entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Api) Unwrap() *Api {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Api is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Api) String() string {
	var builder strings.Builder
	builder.WriteString("Api(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("alias=")
	builder.WriteString(_m.Alias)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("method=")
	builder.WriteString(_m.Method)
	builder.WriteString(", ")
	builder.WriteString("categoryId=")
	builder.WriteString(_m.CategoryId)
	builder.WriteString(", ")
	builder.WriteString("pricing=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pricing))
	builder.WriteString(", ")
	builder.WriteString("documentation=")
	builder.WriteString(_m.Documentation)
	builder.WriteString(", ")
	builder.WriteString("preScript=")
	builder.WriteString(_m.PreScript)
	builder.WriteString(", ")
	builder.WriteString("postScript=")
	builder.WriteString(_m.PostScript)
	builder.WriteString(", ")
	builder.WriteString("isActive=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("callCount=")
	builder.WriteString(fmt.Sprintf("%v", _m.CallCount))
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Apis is a parsable slice of Api.
type Apis []*Api
