// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shuTwT/nex-api/backend/internal/database/ent/api"
	"github.com/shuTwT/nex-api/backend/internal/database/ent/apiparameter"
	"github.com/shuTwT/nex-api/backend/internal/database/ent/predicate"
)

// ApiParameterUpdate is the builder for updating ApiParameter entities.
type ApiParameterUpdate struct {
	config
	hooks    []Hook
	mutation *ApiParameterMutation
}

// Where appends a list predicates to the ApiParameterUpdate builder.
func (_u *ApiParameterUpdate) Where(ps ...predicate.ApiParameter) *ApiParameterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetApiId sets the "apiId" field.
func (_u *ApiParameterUpdate) SetApiId(v string) *ApiParameterUpdate {
	_u.mutation.SetApiId(v)
	return _u
}

// SetNillableApiId sets the "apiId" field if the given value is not nil.
func (_u *ApiParameterUpdate) SetNillableApiId(v *string) *ApiParameterUpdate {
	if v != nil {
		_u.SetApiId(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ApiParameterUpdate) SetName(v string) *ApiParameterUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApiParameterUpdate) SetNillableName(v *string) *ApiParameterUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ApiParameterUpdate) SetType(v string) *ApiParameterUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ApiParameterUpdate) SetNillableType(v *string) *ApiParameterUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetRequired sets the "required" field.
func (_u *ApiParameterUpdate) SetRequired(v bool) *ApiParameterUpdate {
	_u.mutation.SetRequired(v)
	return _u
}

// SetNillableRequired sets the "required" field if the given value is not nil.
func (_u *ApiParameterUpdate) SetNillableRequired(v *bool) *ApiParameterUpdate {
	if v != nil {
		_u.SetRequired(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ApiParameterUpdate) SetDescription(v string) *ApiParameterUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ApiParameterUpdate) SetNillableDescription(v *string) *ApiParameterUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDefaultValue sets the "defaultValue" field.
func (_u *ApiParameterUpdate) SetDefaultValue(v string) *ApiParameterUpdate {
	_u.mutation.SetDefaultValue(v)
	return _u
}

// SetNillableDefaultValue sets the "defaultValue" field if the given value is not nil.
func (_u *ApiParameterUpdate) SetNillableDefaultValue(v *string) *ApiParameterUpdate {
	if v != nil {
		_u.SetDefaultValue(*v)
	}
	return _u
}

// ClearDefaultValue clears the value of the "defaultValue" field.
func (_u *ApiParameterUpdate) ClearDefaultValue() *ApiParameterUpdate {
	_u.mutation.ClearDefaultValue()
	return _u
}

// SetAPIID sets the "api" edge to the Api entity by ID.
func (_u *ApiParameterUpdate) SetAPIID(id string) *ApiParameterUpdate {
	_u.mutation.SetAPIID(id)
	return _u
}

// SetAPI sets the "api" edge to the Api entity.
func (_u *ApiParameterUpdate) SetAPI(v *Api) *ApiParameterUpdate {
	return _u.SetAPIID(v.ID)
}

// Mutation returns the ApiParameterMutation object of the builder.
func (_u *ApiParameterUpdate) Mutation() *ApiParameterMutation {
	return _u.mutation
}

// ClearAPI clears the "api" edge to the Api entity.
func (_u *ApiParameterUpdate) ClearAPI() *ApiParameterUpdate {
	_u.mutation.ClearAPI()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApiParameterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiParameterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApiParameterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiParameterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiParameterUpdate) check() error {
	if _u.mutation.APICleared() && len(_u.mutation.APIIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiParameter.api"`)
	}
	return nil
}

func (_u *ApiParameterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apiparameter.Table, apiparameter.Columns, sqlgraph.NewFieldSpec(apiparameter.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apiparameter.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(apiparameter.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Required(); ok {
		_spec.SetField(apiparameter.FieldRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(apiparameter.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultValue(); ok {
		_spec.SetField(apiparameter.FieldDefaultValue, field.TypeString, value)
	}
	if _u.mutation.DefaultValueCleared() {
		_spec.ClearField(apiparameter.FieldDefaultValue, field.TypeString)
	}
	if _u.mutation.APICleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apiparameter.APITable,
			Columns: []string{apiparameter.APIColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(api.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apiparameter.APITable,
			Columns: []string{apiparameter.APIColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(api.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apiparameter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApiParameterUpdateOne is the builder for updating a single ApiParameter entity.
type ApiParameterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApiParameterMutation
}

// SetApiId sets the "apiId" field.
func (_u *ApiParameterUpdateOne) SetApiId(v string) *ApiParameterUpdateOne {
	_u.mutation.SetApiId(v)
	return _u
}

// SetNillableApiId sets the "apiId" field if the given value is not nil.
func (_u *ApiParameterUpdateOne) SetNillableApiId(v *string) *ApiParameterUpdateOne {
	if v != nil {
		_u.SetApiId(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ApiParameterUpdateOne) SetName(v string) *ApiParameterUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ApiParameterUpdateOne) SetNillableName(v *string) *ApiParameterUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *ApiParameterUpdateOne) SetType(v string) *ApiParameterUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ApiParameterUpdateOne) SetNillableType(v *string) *ApiParameterUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetRequired sets the "required" field.
func (_u *ApiParameterUpdateOne) SetRequired(v bool) *ApiParameterUpdateOne {
	_u.mutation.SetRequired(v)
	return _u
}

// SetNillableRequired sets the "required" field if the given value is not nil.
func (_u *ApiParameterUpdateOne) SetNillableRequired(v *bool) *ApiParameterUpdateOne {
	if v != nil {
		_u.SetRequired(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ApiParameterUpdateOne) SetDescription(v string) *ApiParameterUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ApiParameterUpdateOne) SetNillableDescription(v *string) *ApiParameterUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetDefaultValue sets the "defaultValue" field.
func (_u *ApiParameterUpdateOne) SetDefaultValue(v string) *ApiParameterUpdateOne {
	_u.mutation.SetDefaultValue(v)
	return _u
}

// SetNillableDefaultValue sets the "defaultValue" field if the given value is not nil.
func (_u *ApiParameterUpdateOne) SetNillableDefaultValue(v *string) *ApiParameterUpdateOne {
	if v != nil {
		_u.SetDefaultValue(*v)
	}
	return _u
}

// ClearDefaultValue clears the value of the "defaultValue" field.
func (_u *ApiParameterUpdateOne) ClearDefaultValue() *ApiParameterUpdateOne {
	_u.mutation.ClearDefaultValue()
	return _u
}

// SetAPIID sets the "api" edge to the Api entity by ID.
func (_u *ApiParameterUpdateOne) SetAPIID(id string) *ApiParameterUpdateOne {
	_u.mutation.SetAPIID(id)
	return _u
}

// SetAPI sets the "api" edge to the Api entity.
func (_u *ApiParameterUpdateOne) SetAPI(v *Api) *ApiParameterUpdateOne {
	return _u.SetAPIID(v.ID)
}

// Mutation returns the ApiParameterMutation object of the builder.
func (_u *ApiParameterUpdateOne) Mutation() *ApiParameterMutation {
	return _u.mutation
}

// ClearAPI clears the "api" edge to the Api entity.
func (_u *ApiParameterUpdateOne) ClearAPI() *ApiParameterUpdateOne {
	_u.mutation.ClearAPI()
	return _u
}

// Where appends a list predicates to the ApiParameterUpdate builder.
func (_u *ApiParameterUpdateOne) Where(ps ...predicate.ApiParameter) *ApiParameterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApiParameterUpdateOne) Select(field string, fields ...string) *ApiParameterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ApiParameter entity.
func (_u *ApiParameterUpdateOne) Save(ctx context.Context) (*ApiParameter, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiParameterUpdateOne) SaveX(ctx context.Context) *ApiParameter {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApiParameterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiParameterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiParameterUpdateOne) check() error {
	if _u.mutation.APICleared() && len(_u.mutation.APIIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiParameter.api"`)
	}
	return nil
}

func (_u *ApiParameterUpdateOne) sqlSave(ctx context.Context) (_node *ApiParameter, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apiparameter.Table, apiparameter.Columns, sqlgraph.NewFieldSpec(apiparameter.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApiParameter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apiparameter.FieldID)
		for _, f := range fields {
			if !apiparameter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apiparameter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(apiparameter.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(apiparameter.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Required(); ok {
		_spec.SetField(apiparameter.FieldRequired, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(apiparameter.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.DefaultValue(); ok {
		_spec.SetField(apiparameter.FieldDefaultValue, field.TypeString, value)
	}
	if _u.mutation.DefaultValueCleared() {
		_spec.ClearField(apiparameter.FieldDefaultValue, field.TypeString)
	}
	if _u.mutation.APICleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apiparameter.APITable,
			Columns: []string{apiparameter.APIColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(api.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apiparameter.APITable,
			Columns: []string{apiparameter.APIColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(api.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ApiParameter{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apiparameter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
