// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shuTwT/nex-api/backend/internal/database/ent/redemptioncode"
)

// RedemptionCode is the model entity for the RedemptionCode schema.
type RedemptionCode struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// PlanId holds the value of the "planId" field.
	PlanId string `json:"planId,omitempty"`
	// PlanName holds the value of the "planName" field.
	PlanName string `json:"planName,omitempty"`
	// Credits holds the value of the "credits" field.
	Credits int `json:"credits,omitempty"`
	// ExpiresAt holds the value of the "expiresAt" field.
	ExpiresAt time.Time `json:"expiresAt,omitempty"`
	// IsUsed holds the value of the "isUsed" field.
	IsUsed bool `json:"isUsed,omitempty"`
	// UsedBy holds the value of the "usedBy" field.
	UsedBy string `json:"usedBy,omitempty"`
	// UsedAt holds the value of the "usedAt" field.
	UsedAt time.Time `json:"usedAt,omitempty"`
	// CreatedBy holds the value of the "createdBy" field.
	CreatedBy string `json:"createdBy,omitempty"`
	// BatchId holds the value of the "batchId" field.
	BatchId string `json:"batchId,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt    time.Time `json:"updatedAt,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RedemptionCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case redemptioncode.FieldIsUsed:
			values[i] = new(sql.NullBool)
		case redemptioncode.FieldCredits:
			values[i] = new(sql.NullInt64)
		case redemptioncode.FieldID, redemptioncode.FieldCode, redemptioncode.FieldType, redemptioncode.FieldPlanId, redemptioncode.FieldPlanName, redemptioncode.FieldUsedBy, redemptioncode.FieldCreatedBy, redemptioncode.FieldBatchId:
			values[i] = new(sql.NullString)
		case redemptioncode.FieldExpiresAt, redemptioncode.FieldUsedAt, redemptioncode.FieldCreatedAt, redemptioncode.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RedemptionCode fields.
func (_m *RedemptionCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case redemptioncode.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case redemptioncode.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case redemptioncode.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case redemptioncode.FieldPlanId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field planId", values[i])
			} else if value.Valid {
				_m.PlanId = value.String
			}
		case redemptioncode.FieldPlanName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field planName", values[i])
			} else if value.Valid {
				_m.PlanName = value.String
			}
		case redemptioncode.FieldCredits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field credits", values[i])
			} else if value.Valid {
				_m.Credits = int(value.Int64)
			}
		case redemptioncode.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expiresAt", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case redemptioncode.FieldIsUsed:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field isUsed", values[i])
			} else if value.Valid {
				_m.IsUsed = value.Bool
			}
		case redemptioncode.FieldUsedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field usedBy", values[i])
			} else if value.Valid {
				_m.UsedBy = value.String
			}
		case redemptioncode.FieldUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field usedAt", values[i])
			} else if value.Valid {
				_m.UsedAt = value.Time
			}
		case redemptioncode.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field createdBy", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case redemptioncode.FieldBatchId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field batchId", values[i])
			} else if value.Valid {
				_m.BatchId = value.String
			}
		case redemptioncode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case redemptioncode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RedemptionCode.
// This includes values selected through modifiers, order, etc.
func (_m *RedemptionCode) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RedemptionCode.
// Note that you need to call RedemptionCode.Unwrap() before calling this method if this RedemptionCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RedemptionCode) Update() *RedemptionCodeUpdateOne {
	return NewRedemptionCodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RedemptionCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RedemptionCode) Unwrap() *RedemptionCode {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RedemptionCode is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RedemptionCode) String() string {
	var builder strings.Builder
	builder.WriteString("RedemptionCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("planId=")
	builder.WriteString(_m.PlanId)
	builder.WriteString(", ")
	builder.WriteString("planName=")
	builder.WriteString(_m.PlanName)
	builder.WriteString(", ")
	builder.WriteString("credits=")
	builder.WriteString(fmt.Sprintf("%v", _m.Credits))
	builder.WriteString(", ")
	builder.WriteString("expiresAt=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("isUsed=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsUsed))
	builder.WriteString(", ")
	builder.WriteString("usedBy=")
	builder.WriteString(_m.UsedBy)
	builder.WriteString(", ")
	builder.WriteString("usedAt=")
	builder.WriteString(_m.UsedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("createdBy=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("batchId=")
	builder.WriteString(_m.BatchId)
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RedemptionCodes is a parsable slice of RedemptionCode.
type RedemptionCodes []*RedemptionCode
