// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shuTwT/nex-api/backend/internal/database/ent/subscriptionplan"
)

// SubscriptionPlan is the model entity for the SubscriptionPlan schema.
type SubscriptionPlan struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// TotalCredits holds the value of the "totalCredits" field.
	TotalCredits int `json:"totalCredits,omitempty"`
	// SortOrder holds the value of the "sortOrder" field.
	SortOrder int `json:"sortOrder,omitempty"`
	// ValidityDuration holds the value of the "validityDuration" field.
	ValidityDuration int `json:"validityDuration,omitempty"`
	// ValidityUnit holds the value of the "validityUnit" field.
	ValidityUnit string `json:"validityUnit,omitempty"`
	// CreditResetCycle holds the value of the "creditResetCycle" field.
	CreditResetCycle string `json:"creditResetCycle,omitempty"`
	// IsActive holds the value of the "isActive" field.
	IsActive bool `json:"isActive,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionPlanQuery when eager-loading is set.
	Edges        SubscriptionPlanEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SubscriptionPlanEdges holds the relations/edges for other nodes in the graph.
type SubscriptionPlanEdges struct {
	// Subscriptions holds the value of the subscriptions edge.
	Subscriptions []*Subscription `json:"subscriptions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SubscriptionsOrErr returns the Subscriptions value or an error if the edge
// was not loaded in eager-loading.
func (e SubscriptionPlanEdges) SubscriptionsOrErr() ([]*Subscription, error) {
	if e.loadedTypes[0] {
		return e.Subscriptions, nil
	}
	return nil, &NotLoadedError{edge: "subscriptions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionPlan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionplan.FieldIsActive:
			values[i] = new(sql.NullBool)
		case subscriptionplan.FieldPrice:
			values[i] = new(sql.NullFloat64)
		case subscriptionplan.FieldTotalCredits, subscriptionplan.FieldSortOrder, subscriptionplan.FieldValidityDuration:
			values[i] = new(sql.NullInt64)
		case subscriptionplan.FieldID, subscriptionplan.FieldTitle, subscriptionplan.FieldValidityUnit, subscriptionplan.FieldCreditResetCycle:
			values[i] = new(sql.NullString)
		case subscriptionplan.FieldCreatedAt, subscriptionplan.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionPlan fields.
func (_m *SubscriptionPlan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionplan.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case subscriptionplan.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case subscriptionplan.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.Float64
			}
		case subscriptionplan.FieldTotalCredits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field totalCredits", values[i])
			} else if value.Valid {
				_m.TotalCredits = int(value.Int64)
			}
		case subscriptionplan.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sortOrder", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case subscriptionplan.FieldValidityDuration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field validityDuration", values[i])
			} else if value.Valid {
				_m.ValidityDuration = int(value.Int64)
			}
		case subscriptionplan.FieldValidityUnit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field validityUnit", values[i])
			} else if value.Valid {
				_m.ValidityUnit = value.String
			}
		case subscriptionplan.FieldCreditResetCycle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creditResetCycle", values[i])
			} else if value.Valid {
				_m.CreditResetCycle = value.String
			}
		case subscriptionplan.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field isActive", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case subscriptionplan.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case subscriptionplan.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionPlan.
// This includes values selected through modifiers, order, etc.
func (_m *SubscriptionPlan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySubscriptions queries the "subscriptions" edge of the SubscriptionPlan entity.
func (_m *SubscriptionPlan) QuerySubscriptions() *SubscriptionQuery {
	return NewSubscriptionPlanClient(_m.config).QuerySubscriptions(_m)
}

// Update returns a builder for updating this SubscriptionPlan.
// Note that you need to call SubscriptionPlan.Unwrap() before calling this method if this SubscriptionPlan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SubscriptionPlan) Update() *SubscriptionPlanUpdateOne {
	return NewSubscriptionPlanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SubscriptionPlan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SubscriptionPlan) Unwrap() *SubscriptionPlan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionPlan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SubscriptionPlan) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionPlan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	builder.WriteString("totalCredits=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCredits))
	builder.WriteString(", ")
	builder.WriteString("sortOrder=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("validityDuration=")
	builder.WriteString(fmt.Sprintf("%v", _m.ValidityDuration))
	builder.WriteString(", ")
	builder.WriteString("validityUnit=")
	builder.WriteString(_m.ValidityUnit)
	builder.WriteString(", ")
	builder.WriteString("creditResetCycle=")
	builder.WriteString(_m.CreditResetCycle)
	builder.WriteString(", ")
	builder.WriteString("isActive=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionPlans is a parsable slice of SubscriptionPlan.
type SubscriptionPlans []*SubscriptionPlan
