// Code generated by ent, DO NOT EDIT.

package scheduledjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the scheduledjob type in the database.
	Label = "scheduled_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTaskKey holds the string denoting the taskkey field in the database.
	FieldTaskKey = "taskKey"
	// FieldScheduleType holds the string denoting the scheduletype field in the database.
	FieldScheduleType = "scheduleType"
	// FieldExpression holds the string denoting the expression field in the database.
	FieldExpression = "expression"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldLastRunAt holds the string denoting the lastrunat field in the database.
	FieldLastRunAt = "lastRunAt"
	// FieldLastStatus holds the string denoting the laststatus field in the database.
	FieldLastStatus = "lastStatus"
	// FieldLastError holds the string denoting the lasterror field in the database.
	FieldLastError = "lastError"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "createdAt"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updatedAt"
	// Table holds the table name of the scheduledjob in the database.
	Table = "ScheduledJob"
)

// Columns holds all SQL columns for scheduledjob fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldTaskKey,
	FieldScheduleType,
	FieldExpression,
	FieldEnabled,
	FieldDescription,
	FieldLastRunAt,
	FieldLastStatus,
	FieldLastError,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultLastStatus holds the default value on creation for the "lastStatus" field.
	DefaultLastStatus string
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updatedAt" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the ScheduledJob queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByTaskKey orders the results by the taskKey field.
func ByTaskKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskKey, opts...).ToFunc()
}

// ByScheduleType orders the results by the scheduleType field.
func ByScheduleType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScheduleType, opts...).ToFunc()
}

// ByExpression orders the results by the expression field.
func ByExpression(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpression, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByLastRunAt orders the results by the lastRunAt field.
func ByLastRunAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRunAt, opts...).ToFunc()
}

// ByLastStatus orders the results by the lastStatus field.
func ByLastStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastStatus, opts...).ToFunc()
}

// ByLastError orders the results by the lastError field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
