import {
  Activity,
  Airplay,
  AlarmClock,
  Archive,
  Atom,
  Award,
  BadgeCheck,
  BarChart3,
  Banknote,
  Bell,
  Blocks,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Boxes,
  Braces,
  Brain,
  Briefcase,
  Bug,
  Building2,
  Cable,
  Calculator,
  Calendar,
  Camera,
  Car,
  CheckCircle2,
  ChevronRight,
  CircleDollarSign,
  CircuitBoard,
  Clipboard,
  Clock,
  Cloud,
  CloudRain,
  Code,
  Code2,
  Coins,
  Compass,
  Component,
  CreditCard,
  Crown,
  Database,
  Dna,
  DollarSign,
  Download,
  Drum,
  Dumbbell,
  Eye,
  File,
  FileCode2,
  FileText,
  Filter,
  Fingerprint,
  Flame,
  FlaskConical,
  Folder,
  FolderOpen,
  Fuel,
  Gauge,
  Gem,
  GitBranch,
  GitMerge,
  Globe,
  GraduationCap,
  Grid3x3,
  Hand,
  HardDrive,
  Headphones,
  Heart,
  Home,
  Infinity as InfinityIcon,
  Image,
  Inbox,
  Key,
  KeyRound,
  Languages,
  Laptop,
  LayoutDashboard,
  Layers,
  Leaf,
  Library,
  LifeBuoy,
  Lightbulb,
  LineChart,
  Link,
  Loader,
  Lock,
  Mail,
  Map as MapIcon,
  MapPin,
  Medal,
  MemoryStick,
  MessageCircle,
  MessageSquare,
  Microscope,
  Monitor,
  Moon,
  Music,
  Navigation,
  Network,
  Newspaper,
  Package,
  PackageCheck,
  Paintbrush,
  Palette,
  Paperclip,
  Percent,
  Phone,
  PieChart,
  Plane,
  Play,
  Plug,
  PlugZap,
  Puzzle,
  QrCode,
  Radio,
  Rocket,
  Rss,
  Route,
  Scan,
  Search,
  Send,
  Server,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Snowflake,
  Sparkles,
  Star,
  Store,
  Sun,
  Tablet,
  Tag,
  Target,
  Terminal,
  TestTube2,
  ThumbsUp,
  Ticket,
  Timer,
  TrendingDown,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Unlock,
  Upload,
  Users,
  Video,
  Wallet,
  Wand2,
  Watch,
  Waves,
  Webhook,
  Wifi,
  Wind,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export interface IconEntry {
  /** lucide-react 组件的 PascalCase 名称，与数据库中存储的 icon 字段一致 */
  name: string;
  icon: LucideIcon;
  /** 中文名称与搜索关键词（小写） */
  keywords: string;
}

// 精选常用图标；显式引入以保持 tree-shaking，新增入口请同步补充关键词。
export const ICON_REGISTRY: IconEntry[] = [
  { name: "Activity", icon: Activity, keywords: "activity 活动 心跳 监控" },
  { name: "Airplay", icon: Airplay, keywords: "airplay 投屏 屏幕" },
  { name: "AlarmClock", icon: AlarmClock, keywords: "alarm 闹钟 时间" },
  { name: "Archive", icon: Archive, keywords: "archive 归档 存储" },
  { name: "Atom", icon: Atom, keywords: "atom 原子 科学" },
  { name: "Award", icon: Award, keywords: "award 奖章 荣誉" },
  { name: "BadgeCheck", icon: BadgeCheck, keywords: "badge 徽章 认证 通过" },
  { name: "Banknote", icon: Banknote, keywords: "banknote 钞票 现金 钱支付" },
  { name: "BarChart3", icon: BarChart3, keywords: "chart 图表 统计 报表" },
  { name: "Bell", icon: Bell, keywords: "bell 铃铛 通知 消息" },
  { name: "Blocks", icon: Blocks, keywords: "blocks 积木 模块 组件" },
  { name: "BookOpen", icon: BookOpen, keywords: "book 书 文档 教程" },
  { name: "Bookmark", icon: Bookmark, keywords: "bookmark 书签 收藏" },
  { name: "Bot", icon: Bot, keywords: "bot 机器人 AI 智能" },
  { name: "Box", icon: Box, keywords: "box 盒子 容器" },
  { name: "Boxes", icon: Boxes, keywords: "boxes 盒子组 库存 批量" },
  { name: "Braces", icon: Braces, keywords: "braces 括号 代码 json" },
  { name: "Brain", icon: Brain, keywords: "brain 大脑 AI 智能 模型" },
  { name: "Briefcase", icon: Briefcase, keywords: "briefcase 公文包 商务 工作" },
  { name: "Bug", icon: Bug, keywords: "bug 漏洞 调试 缺陷" },
  { name: "Building2", icon: Building2, keywords: "building 大楼 企业 公司" },
  { name: "Cable", icon: Cable, keywords: "cable 线缆 连接" },
  { name: "Calculator", icon: Calculator, keywords: "calculator 计算器 数学" },
  { name: "Calendar", icon: Calendar, keywords: "calendar 日历 日期 计划" },
  { name: "Camera", icon: Camera, keywords: "camera 相机 拍照 摄影" },
  { name: "Car", icon: Car, keywords: "car 汽车 出行 交通" },
  { name: "CheckCircle2", icon: CheckCircle2, keywords: "check 完成 成功 勾" },
  { name: "ChevronRight", icon: ChevronRight, keywords: "chevron 箭头 右 展开子级" },
  { name: "CircleDollarSign", icon: CircleDollarSign, keywords: "dollar 美元 金钱 计费" },
  { name: "CircuitBoard", icon: CircuitBoard, keywords: "circuit 电路 芯片 硬件" },
  { name: "Clipboard", icon: Clipboard, keywords: "clipboard 剪贴板 复制 粘贴" },
  { name: "Clock", icon: Clock, keywords: "clock 时钟 时间 定时" },
  { name: "Cloud", icon: Cloud, keywords: "cloud 云 云服务" },
  { name: "CloudRain", icon: CloudRain, keywords: "rain 雨 天气" },
  { name: "Code", icon: Code, keywords: "code 代码 开发" },
  { name: "Code2", icon: Code2, keywords: "code 代码 开发 编程" },
  { name: "Coins", icon: Coins, keywords: "coins 硬币 积分 额度" },
  { name: "Compass", icon: Compass, keywords: "compass 指南针 导航 探索" },
  { name: "Component", icon: Component, keywords: "component 组件 零件" },
  { name: "CreditCard", icon: CreditCard, keywords: "credit 银行卡 信用卡 支付" },
  { name: "Crown", icon: Crown, keywords: "crown 皇冠 会员 VIP 高级" },
  { name: "Database", icon: Database, keywords: "database 数据库 存储 数据" },
  { name: "Dna", icon: Dna, keywords: "dna 基因 生物" },
  { name: "DollarSign", icon: DollarSign, keywords: "dollar 美元 价格 计费" },
  { name: "Download", icon: Download, keywords: "download 下载" },
  { name: "Drum", icon: Drum, keywords: "drum 鼓 音乐 乐器" },
  { name: "Dumbbell", icon: Dumbbell, keywords: "dumbbell 哑铃 健身 运动" },
  { name: "Eye", icon: Eye, keywords: "eye 眼睛 查看 预览" },
  { name: "File", icon: File, keywords: "file 文件" },
  { name: "FileCode2", icon: FileCode2, keywords: "file 代码文件 脚本" },
  { name: "FileText", icon: FileText, keywords: "file 文本 文档 报告" },
  { name: "Filter", icon: Filter, keywords: "filter 筛选 过滤" },
  { name: "Fingerprint", icon: Fingerprint, keywords: "fingerprint 指纹 安全 身份" },
  { name: "Flame", icon: Flame, keywords: "flame 火焰 热门 燃烧" },
  { name: "FlaskConical", icon: FlaskConical, keywords: "flask 烧杯 实验 科学 测试" },
  { name: "Folder", icon: Folder, keywords: "folder 文件夹 目录" },
  { name: "FolderOpen", icon: FolderOpen, keywords: "folder 打开的文件夹 目录" },
  { name: "Fuel", icon: Fuel, keywords: "fuel 燃油 加油" },
  { name: "Gauge", icon: Gauge, keywords: "gauge 仪表 盘 限流 指标" },
  { name: "Gem", icon: Gem, keywords: "gem 宝石 钻石 高级" },
  { name: "GitBranch", icon: GitBranch, keywords: "git 分支 版本" },
  { name: "GitMerge", icon: GitMerge, keywords: "git 合并 版本" },
  { name: "Globe", icon: Globe, keywords: "globe 地球 全球 网络 国际" },
  { name: "GraduationCap", icon: GraduationCap, keywords: "graduation 教育 学习 课程" },
  { name: "Grid3x3", icon: Grid3x3, keywords: "grid 网格 全部 分类" },
  { name: "Hand", icon: Hand, keywords: "hand 手势 互动" },
  { name: "HardDrive", icon: HardDrive, keywords: "drive 硬盘 存储 服务器" },
  { name: "Headphones", icon: Headphones, keywords: "headphones 耳机 音频 听" },
  { name: "Heart", icon: Heart, keywords: "heart 心 喜欢 收藏 健康" },
  { name: "Home", icon: Home, keywords: "home 首页 房子" },
  { name: "InfinityIcon", icon: InfinityIcon, keywords: "infinity 无限 无限制" },
  { name: "Image", icon: Image, keywords: "image 图片 照片 绘图" },
  { name: "Inbox", icon: Inbox, keywords: "inbox 收件箱 邮箱" },
  { name: "Key", icon: Key, keywords: "key 钥匙 密钥 API key" },
  { name: "KeyRound", icon: KeyRound, keywords: "key 密钥 令牌 鉴权" },
  { name: "Languages", icon: Languages, keywords: "languages 语言 翻译 多语言" },
  { name: "Laptop", icon: Laptop, keywords: "laptop 笔记本 电脑" },
  { name: "LayoutDashboard", icon: LayoutDashboard, keywords: "dashboard 仪表盘 控制台 面板" },
  { name: "Layers", icon: Layers, keywords: "layers 图层 层级 架构" },
  { name: "Leaf", icon: Leaf, keywords: "leaf 叶子 环保 植物 自然" },
  { name: "Library", icon: Library, keywords: "library 图书馆 资源库 素材" },
  { name: "LifeBuoy", icon: LifeBuoy, keywords: "buoy 救生圈 帮助 支持" },
  { name: "Lightbulb", icon: Lightbulb, keywords: "bulb 灯泡 想法 创意 提示" },
  { name: "LineChart", icon: LineChart, keywords: "chart 折线图 趋势 统计" },
  { name: "Link", icon: Link, keywords: "link 链接 url 网址" },
  { name: "Loader", icon: Loader, keywords: "loader 加载 转圈 spinner" },
  { name: "Lock", icon: Lock, keywords: "lock 锁 加密 安全 私有" },
  { name: "Mail", icon: Mail, keywords: "mail 邮件 邮箱 发信" },
  { name: "Map", icon: MapIcon, keywords: "map 地图 位置" },
  { name: "MapPin", icon: MapPin, keywords: "pin 定位 位置 地址" },
  { name: "Medal", icon: Medal, keywords: "medal 奖牌 排名 等级" },
  { name: "MemoryStick", icon: MemoryStick, keywords: "memory 内存 硬件" },
  { name: "MessageCircle", icon: MessageCircle, keywords: "message 聊天 对话 客服" },
  { name: "MessageSquare", icon: MessageSquare, keywords: "message 留言 消息 评论" },
  { name: "Microscope", icon: Microscope, keywords: "microscope 显微镜 科研" },
  { name: "Monitor", icon: Monitor, keywords: "monitor 显示器 屏幕 电脑" },
  { name: "Moon", icon: Moon, keywords: "moon 月亮 夜间 暗色" },
  { name: "Music", icon: Music, keywords: "music 音乐 音频 歌曲" },
  { name: "Navigation", icon: Navigation, keywords: "navigation 导航 方向" },
  { name: "Network", icon: Network, keywords: "network 网络 节点 拓扑" },
  { name: "Newspaper", icon: Newspaper, keywords: "newspaper 新闻 资讯 公告" },
  { name: "Package", icon: Package, keywords: "package 包裹 套餐 发布" },
  { name: "PackageCheck", icon: PackageCheck, keywords: "package 打包 完成 套餐" },
  { name: "Paintbrush", icon: Paintbrush, keywords: "paint 刷子 绘画 美术" },
  { name: "Palette", icon: Palette, keywords: "palette 调色板 设计 颜色" },
  { name: "Paperclip", icon: Paperclip, keywords: "paperclip 回形针 附件" },
  { name: "Percent", icon: Percent, keywords: "percent 百分比 折扣 优惠" },
  { name: "Phone", icon: Phone, keywords: "phone 电话 语音 通讯" },
  { name: "PieChart", icon: PieChart, keywords: "chart 饼图 占比 统计" },
  { name: "Plane", icon: Plane, keywords: "plane 飞机 旅行 出行" },
  { name: "Play", icon: Play, keywords: "play 播放 开始 视频" },
  { name: "Plug", icon: Plug, keywords: "plug 插头 接入 对接" },
  { name: "PlugZap", icon: PlugZap, keywords: "plug 即插即用 接入 快速" },
  { name: "Puzzle", icon: Puzzle, keywords: "puzzle 拼图 插件 扩展" },
  { name: "QrCode", icon: QrCode, keywords: "qrcode 二维码 扫码" },
  { name: "Radio", icon: Radio, keywords: "radio 电台 广播 广播流" },
  { name: "Rocket", icon: Rocket, keywords: "rocket 火箭 发布 加速 上线" },
  { name: "Rss", icon: Rss, keywords: "rss 订阅 聚合 feed" },
  { name: "Route", icon: Route, keywords: "route 路由 线路 路径" },
  { name: "Scan", icon: Scan, keywords: "scan 扫描 识别 ocr" },
  { name: "Search", icon: Search, keywords: "search 搜索 查找" },
  { name: "Send", icon: Send, keywords: "send 发送 推送 邮件" },
  { name: "Server", icon: Server, keywords: "server 服务器 主机 部署" },
  { name: "Share2", icon: Share2, keywords: "share 分享 传播" },
  { name: "Shield", icon: Shield, keywords: "shield 盾牌 安全 防护" },
  { name: "ShieldCheck", icon: ShieldCheck, keywords: "shield 安全 校验 通过 防护" },
  { name: "ShoppingBag", icon: ShoppingBag, keywords: "shopping 购物袋 商品 商城" },
  { name: "ShoppingCart", icon: ShoppingCart, keywords: "cart 购物车 下单 购买" },
  { name: "Smartphone", icon: Smartphone, keywords: "phone 手机 移动端" },
  { name: "Snowflake", icon: Snowflake, keywords: "snowflake 雪花 冷冻 冬天" },
  { name: "Sparkles", icon: Sparkles, keywords: "sparkles 闪光 智能 AI 推荐 魔法" },
  { name: "Star", icon: Star, keywords: "star 星星 收藏 评分 精选" },
  { name: "Store", icon: Store, keywords: "store 商店 店铺 市集" },
  { name: "Sun", icon: Sun, keywords: "sun 太阳 白天 亮色" },
  { name: "Tablet", icon: Tablet, keywords: "tablet 平板 设备" },
  { name: "Tag", icon: Tag, keywords: "tag 标签 分类 标记" },
  { name: "Target", icon: Target, keywords: "target 目标 精准 定位" },
  { name: "Terminal", icon: Terminal, keywords: "terminal 终端 命令行 脚本" },
  { name: "TestTube2", icon: TestTube2, keywords: "test 试管 测试 实验" },
  { name: "ThumbsUp", icon: ThumbsUp, keywords: "thumbs 点赞 好评 推荐" },
  { name: "Ticket", icon: Ticket, keywords: "ticket 票券 工单 优惠" },
  { name: "Timer", icon: Timer, keywords: "timer 计时器 倒计时" },
  { name: "TrendingDown", icon: TrendingDown, keywords: "trend 下降 趋势" },
  { name: "TrendingUp", icon: TrendingUp, keywords: "trend 上升 趋势 增长" },
  { name: "Trophy", icon: Trophy, keywords: "trophy 奖杯 冠军 排行榜" },
  { name: "Truck", icon: Truck, keywords: "truck 卡车 物流 配送" },
  { name: "Tv", icon: Tv, keywords: "tv 电视 视频 直播" },
  { name: "Umbrella", icon: Umbrella, keywords: "umbrella 雨伞 保险 天气" },
  { name: "Unlock", icon: Unlock, keywords: "unlock 解锁 开锁" },
  { name: "Upload", icon: Upload, keywords: "upload 上传 导入" },
  { name: "Users", icon: Users, keywords: "users 用户群 客户 团队 成员" },
  { name: "Video", icon: Video, keywords: "video 视频 摄像 影像" },
  { name: "Wallet", icon: Wallet, keywords: "wallet 钱包 余额 充值" },
  { name: "Wand2", icon: Wand2, keywords: "wand 魔法棒 AI 生成 魔法" },
  { name: "Watch", icon: Watch, keywords: "watch 手表 穿戴设备" },
  { name: "Waves", icon: Waves, keywords: "waves 波浪 音频 水波" },
  { name: "Webhook", icon: Webhook, keywords: "webhook 回调 推送 钩子" },
  { name: "Wifi", icon: Wifi, keywords: "wifi 无线 网络 信号" },
  { name: "Wind", icon: Wind, keywords: "wind 风 天气 空气" },
  { name: "Workflow", icon: Workflow, keywords: "workflow 工作流 流程 自动化" },
  { name: "Wrench", icon: Wrench, keywords: "wrench 扳手 工具 维修 配置" },
  { name: "Zap", icon: Zap, keywords: "zap 闪电 速度 能量 快" },
];

/** 名称到条目的索引，用于按数据库存储的 icon 字段渲染图标。 */
const ICON_INDEX = new Map(ICON_REGISTRY.map((entry) => [entry.name, entry]));

/** 按存储名取图标；未收录或为空时回退到 Sparkles。 */
export function getIcon(name: string | null | undefined): LucideIcon {
  return ICON_INDEX.get(name ?? "")?.icon ?? Sparkles;
}
